services:
  - id: phoenix
    image: boostport/hbase-phoenix-all-in-one:1.2-4.11
    ports:
      - "8765"

dev:
  image: golang:1.8-alpine
  env:
    AVATICA_HOST: http://phoenix:8765
  steps:
    - type: script
      name: Set up workspace
      options:
        command: mkdir -p "$GOPATH/src/github.com/Boostport" && ln -s /source $GOPATH/src/github.com/apache/calcite-avatica-go

  reload:
    - type: script
      name: Run tests
      cwd: $GOPATH/src/github.com/apache/calcite-avatica-go
      options:
        command: go test -v $(go list ./... | grep -v /vendor/)