services:
  - id: zookeeper
    image: f21global/zookeeper:latest
    env:
      CONFIGTYPE: file
    ports:
      - "8080"

  - id: jn1
    image: f21global/hdfs-journalnode:latest
    env:
      CLUSTER_NAME: mycluster
    ports:
      - "8480:8480"

  - id: jn2
    image: f21global/hdfs-journalnode:latest
    env:
      CLUSTER_NAME: mycluster
    ports:
      - "8481:8480"

  - id: jn3
    image: f21global/hdfs-journalnode:latest
    env:
      CLUSTER_NAME: mycluster
    ports:
      - "8482:8480"

  - id: nn1
    image: f21global/hdfs-namenode:latest
    env:
      CLUSTER_NAME: mycluster
      DFS_NAMESERVICE_ID: ns1
      DFS_NAMENODE_SHARED_EDITS_DIR: $MOBY_JN1_FQDN:8485,$MOBY_JN2_FQDN:8485,$MOBY_JN3_FQDN:8485
      DFS_NAMENODE_RPC_ADDRESS_NN1: $MOBY_NN1_FQDN:8020
      DFS_NAMENODE_RPC_ADDRESS_NN2: $MOBY_NN2_FQDN:8020
      DFS_NAMENODE_HTTP_ADDRESS_NN1: $MOBY_NN1_FQDN:50070
      DFS_NAMENODE_HTTP_ADDRESS_NN2: $MOBY_NN2_FQDN:50070
      HA_ZOOKEEPER_QUORUM: $MOBY_ZOOKEEPER_FQDN:2181
    ports:
      - "50070:50070"

  - id: nn2
    image: f21global/hdfs-namenode:latest
    env:
      CLUSTER_NAME: mycluster
      DFS_NAMESERVICE_ID: ns1
      DFS_NAMENODE_SHARED_EDITS_DIR: $MOBY_JN1_FQDN:8485,$MOBY_JN2_FQDN:8485,$MOBY_JN3_FQDN:8485
      DFS_NAMENODE_RPC_ADDRESS_NN1: $MOBY_NN1_FQDN:8020
      DFS_NAMENODE_RPC_ADDRESS_NN2: $MOBY_NN2_FQDN:8020
      DFS_NAMENODE_HTTP_ADDRESS_NN1: $MOBY_NN1_FQDN:50070
      DFS_NAMENODE_HTTP_ADDRESS_NN2: $MOBY_NN2_FQDN:50070
      HA_ZOOKEEPER_QUORUM: $MOBY_ZOOKEEPER_FQDN:2181
      STANDBY: "true"
    ports:
      - "50071:50070"

  - id: dn1
    image: f21global/hdfs-datanode:latest
    env:
      DFS_NAMESERVICES: ns1
      NS1_DFS_NAMENODE_RPC_ADDRESS_NN1: $MOBY_NN1_FQDN:8020
      NS1_DFS_NAMENODE_RPC_ADDRESS_NN2: $MOBY_NN2_FQDN:8020
      NS1_DFS_NAMENODE_HTTP_ADDRESS_NN1: $MOBY_NN1_FQDN:50070
      NS1_DFS_NAMENODE_HTTP_ADDRESS_NN2: $MOBY_NN2_FQDN:50070
    ports:
      - "50076:50075"

  - id: dn2
    image: f21global/hdfs-datanode:latest
    env:
      DFS_NAMESERVICES: ns1
      NS1_DFS_NAMENODE_RPC_ADDRESS_NN1: $MOBY_NN1_FQDN:8020
      NS1_DFS_NAMENODE_RPC_ADDRESS_NN2: $MOBY_NN2_FQDN:8020
      NS1_DFS_NAMENODE_HTTP_ADDRESS_NN1: $MOBY_NN1_FQDN:50070
      NS1_DFS_NAMENODE_HTTP_ADDRESS_NN2: $MOBY_NN2_FQDN:50070
    ports:
      - "50077:50075"

  - id: dn3
    image: f21global/hdfs-datanode:latest
    env:
      DFS_NAMESERVICES: ns1
      NS1_DFS_NAMENODE_RPC_ADDRESS_NN1: $MOBY_NN1_FQDN:8020
      NS1_DFS_NAMENODE_RPC_ADDRESS_NN2: $MOBY_NN2_FQDN:8020
      NS1_DFS_NAMENODE_HTTP_ADDRESS_NN1: $MOBY_NN1_FQDN:50070
      NS1_DFS_NAMENODE_HTTP_ADDRESS_NN2: $MOBY_NN2_FQDN:50070
    ports:
      - "50078:50075"

  - id: hmaster1
    image: f21global/hbase-master-phoenix:latest
    env:
      CLUSTER_NAME: hbase
      HBASE_ZOOKEEPER_QUORUM: $MOBY_ZOOKEEPER_FQDN
      HDFS_CLUSTER_NAME: mycluster
      DFS_NAMENODE_RPC_ADDRESS_NN1: $MOBY_NN1_FQDN:8020
      DFS_NAMENODE_RPC_ADDRESS_NN2: $MOBY_NN2_FQDN:8020
      DFS_NAMENODE_HTTP_ADDRESS_NN1: $MOBY_NN1_FQDN:50070
      DFS_NAMENODE_HTTP_ADDRESS_NN2: $MOBY_NN2_FQDN:50070
    ports:
      - "16010"

  - id: hregion1
    image: f21global/hbase-regionserver-phoenix:latest
    env:
      CLUSTER_NAME: hbase
      HBASE_ZOOKEEPER_QUORUM: $MOBY_ZOOKEEPER_FQDN
      HDFS_CLUSTER_NAME: mycluster
      DFS_NAMENODE_RPC_ADDRESS_NN1: $MOBY_NN1_FQDN:8020
      DFS_NAMENODE_RPC_ADDRESS_NN2: $MOBY_NN2_FQDN:8020
      DFS_NAMENODE_HTTP_ADDRESS_NN1: $MOBY_NN1_FQDN:50070
      DFS_NAMENODE_HTTP_ADDRESS_NN2: $MOBY_NN2_FQDN:50070
    ports:
      - "16030"

  - id: phoenix-server
    image: f21global/hbase-phoenix-server:latest
    env:
      HBASE_ZOOKEEPER_QUORUM: $MOBY_ZOOKEEPER_FQDN
      ZOOKEEPER_ZNODE_PARENT: hbase
      HBASE_CLUSTER_NAME: hbase
    ports:
      - "8765"

dev:
  image: golang:latest
  env:
    AVATICA_HOST: http://phoenix-server:8765
  steps:
    - type: script
      name: Set up workspace
      options:
        command: mkdir -p "$GOPATH/src/github.com/Boostport" && ln -s /source $GOPATH/src/github.com/Boostport/avatica

  reload:
    - type: script
      name: Run tests
      cwd: $GOPATH/src/github.com/Boostport/avatica
      options:
        command: go test $(go list ./... | grep -v /vendor/)