/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package prompt

import "github.com/c-bata/go-prompt"

func CustomCompleter(d prompt.Document) []prompt.Suggest {
    input := d.GetWordBeforeCursor()
    if input == "" {
        return nil // Return an empty suggestion list when the input is empty
    }

    suggestions := []prompt.Suggest{
		{Text: "ABS", Description: "Returns the absolute value of a numeric expression."},
		{Text: "ABSENT", Description: "Indicates that a pattern or match condition is absent."},
		{Text: "ABSOLUTE", Description: "Specifies an absolute point in time or position."},
		{Text: "ACTION", Description: "Defines the action to be performed in a trigger or event."},
		{Text: "ADA", Description: "Indicates support for the Ada programming language."},
		{Text: "ADD", Description: "Adds two numeric values or concatenates two strings."},
		{Text: "ADMIN", Description: "Specifies administrative privileges."},
		{Text: "AFTER", Description: "Defines actions to be performed after an event or time."},
		{Text: "ALL", Description: "Specifies all rows or all elements in a set."},
		{Text: "ALLOCATE", Description: "Allocates resources for a cursor or statement."},
		{Text: "ALLOW", Description: "Grants permission or access to a specific action."},
		{Text: "ALTER", Description: "Modifies a database object's structure or settings."},
		{Text: "ALWAYS", Description: "Specifies a condition or action that is always true or applied."},
		{Text: "AND", Description: "A logical operator representing a conjunction (AND)."},
		{Text: "ANY", Description: "Indicates any row or any element in a set."},
		{Text: "APPLY", Description: "Applies a function to a set of arguments or inputs."},
		{Text: "ARE", Description: "Indicates a Boolean comparison of two values."},
		{Text: "ARRAY", Description: "Defines a collection of elements of the same data type."},
		{Text: "ARRAY_AGG", Description: "Aggregates elements into an array."},
		{Text: "ARRAY_CONCAT_AGG", Description: "Concatenates arrays into a single array."},
		{Text: "ARRAY_MAX_CARDINALITY", Description: "Returns the maximum cardinality of an array."},
		{Text: "AS", Description: "Defines an alias for a table, column, or result set."},
		{Text: "ASC", Description: "Specifies ascending order in sorting."},
		{Text: "ASENSITIVE", Description: "Indicates insensitivity to accent or case."},
		{Text: "ASSERTION", Description: "Defines a condition that data must conform to."},
		{Text: "ASSIGNMENT", Description: "Assigns a value to a variable or attribute."},
		{Text: "ASYMMETRIC", Description: "Indicates asymmetric encryption or comparison."},
		{Text: "AT", Description: "Defines a point in time or a location in a data stream."},
		{Text: "ATOMIC", Description: "Specifies an atomic transaction."},
		{Text: "ATTRIBUTE", Description: "Represents a characteristic or property of an object."},
		{Text: "ATTRIBUTES", Description: "Specifies the attributes of a data type."},
		{Text: "AUTHORIZATION", Description: "Specifies the access rights or permissions of a user."},
		{Text: "AVG", Description: "Calculates the average of a set of numeric values."},
		{Text: "BEFORE", Description: "Defines actions to be performed before an event or time."},
		{Text: "BEGIN", Description: "Starts a block of executable statements."},
		{Text: "BEGIN_FRAME", Description: "Marks the start of a frame within a window function."},
		{Text: "BEGIN_PARTITION", Description: "Marks the start of a partition within a window function."},
		{Text: "BERNOULLI", Description: "Defines a random sampling technique."},
		{Text: "BETWEEN", Description: "Checks if a value is within a specified range."},
		{Text: "BIGINT", Description: "Represents a large integer data type."},
		{Text: "BINARY", Description: "Specifies a binary string or binary data."},
		{Text: "BIT", Description: "Represents a bit data type."},
		{Text: "BLOB", Description: "Represents a large binary object data type."},
		{Text: "BOOLEAN", Description: "Represents a Boolean data type."},
		{Text: "BOTH", Description: "Specifies a condition that applies to both operands."},
		{Text: "BREADTH", Description: "Specifies breadth-first search in a graph."},
		{Text: "BY", Description: "Defines the grouping or ordering of query results."},
		{Text: "C", Description: "Represents the C programming language."},
		{Text: "CALL", Description: "Executes a stored procedure or function."},
		{Text: "CALLED", Description: "Indicates a function or procedure that is called."},
		{Text: "CARDINALITY", Description: "Returns the number of elements in an array."},
		{Text: "CASCADE", Description: "Specifies that an action applies to related elements."},
		{Text: "CASCADED", Description: "Specifies a series of actions performed in sequence."},
		{Text: "CASE", Description: "Performs conditional logic in a query or expression."},
		{Text: "CAST", Description: "Converts a data type to another data type."},
		{Text: "CATALOG", Description: "Represents a catalog in a database."},
		{Text: "CATALOG_NAME", Description: "Returns the name of a catalog."},
		{Text: "CEIL", Description: "Returns the smallest integer greater than or equal to a number."},
		{Text: "CEILING", Description: "Returns the smallest integer greater than or equal to a number."},
		{Text: "CENTURY", Description: "Represents a century in a date or time."},
		{Text: "CHAIN", Description: "Specifies the order of objects or operations."},
		{Text: "CHAR", Description: "Represents a fixed-length character string."},
		{Text: "CHARACTER", Description: "Represents a fixed-length character string."},
		{Text: "CHARACTERISTICS", Description: "Specifies the characteristics of a data type."},
		{Text: "CHARACTERS", Description: "Returns the number of characters in a string."},
		{Text: "CHARACTER_LENGTH", Description: "Returns the number of characters in a string."},
		{Text: "CHARACTER_SET_CATALOG", Description: "Returns the name of the catalog containing the character set."},
		{Text: "CHARACTER_SET_NAME", Description: "Returns the name of the character set."},
		{Text: "CHARACTER_SET_SCHEMA", Description: "Returns the schema of the character set."},
		{Text: "CHAR_LENGTH", Description: "Returns the number of characters in a string."},
		{Text: "CHECK", Description: "Defines a condition that must be true for data to be valid."},
		{Text: "CLASSIFIER", Description: "Applies a classification algorithm to data."},
		{Text: "CLASS_ORIGIN", Description: "Returns the origin of a user-defined type."},
		{Text: "CLOB", Description: "Represents a large character object data type."},
		{Text: "CLOSE", Description: "Closes a cursor or a file."},
		{Text: "COALESCE", Description: "Returns the first non-null expression in a list."},
		{Text: "COBOL", Description: "Indicates support for the COBOL programming language."},
		{Text: "COLLATE", Description: "Specifies the collation sequence for character string comparison."},
		{Text: "COLLATION", Description: "Specifies the collation sequence for character string comparison."},
		{Text: "COLLATION_CATALOG", Description: "Returns the name of the catalog containing the collation."},
		{Text: "COLLATION_NAME", Description: "Returns the name of the collation."},
		{Text: "COLLATION_SCHEMA", Description: "Returns the schema of the collation."},
		{Text: "COLLECT", Description: "Aggregates values into a collection."},
		{Text: "COLUMN", Description: "Represents a column in a table."},
		{Text: "COLUMN_NAME", Description: "Returns the name of a column."},
		{Text: "COMMAND_FUNCTION", Description: "Specifies the function invoked by a command."},
		{Text: "COMMAND_FUNCTION_CODE", Description: "Returns the code of the command function."},
		{Text: "COMMIT", Description: "Permanently saves the changes made in a transaction."},
		{Text: "COMMITTED", Description: "Indicates a transaction that has been committed."},
		{Text: "CONDITION", Description: "Represents a condition or error code."},
		{Text: "CONDITIONAL", Description: "Specifies a condition that depends on a Boolean expression."},
		{Text: "CONDITION_NUMBER", Description: "Returns the condition number for a condition name."},
		{Text: "CONNECT", Description: "Connects to a database or network service."},
		{Text: "CONNECTION", Description: "Represents a connection to a database or network service."},
		{Text: "CONNECTION_NAME", Description: "Returns the name of a connection."},
		{Text: "CONSTRAINT", Description: "Enforces rules or restrictions on data."},
		{Text: "CONSTRAINTS", Description: "Specifies the constraints on a database object."},
		{Text: "CONSTRAINT_CATALOG", Description: "Returns the name of the catalog containing the constraint."},
		{Text: "CONSTRAINT_NAME", Description: "Returns the name of the constraint."},
		{Text: "CONSTRAINT_SCHEMA", Description: "Returns the schema of the constraint."},
		{Text: "CONSTRUCTOR", Description: "Creates an instance of a user-defined type."},
		{Text: "CONTAINS", Description: "Checks if a value contains a specific element or substring."},
		{Text: "CONTINUE", Description: "Skips the remaining statements in a loop iteration."},
		{Text: "CONVERT", Description: "Converts a value to a specified data type."},
		{Text: "CORR", Description: "Calculates the correlation between two sets of data."},
		{Text: "CORRESPONDING", Description: "Specifies the correspondence between columns in two tables."},
		{Text: "COUNT", Description: "Returns the number of rows in a result set."},
		{Text: "COVAR_POP", Description: "Calculates the population covariance of two sets of data."},
		{Text: "COVAR_SAMP", Description: "Calculates the sample covariance of two sets of data."},
		{Text: "CREATE", Description: "Creates a database, table, view, or other database objects."},
		{Text: "CROSS", Description: "Specifies a Cartesian product of two tables."},
		{Text: "CUBE", Description: "Generates groups with all possible combinations of values."},
		{Text: "CUME_DIST", Description: "Calculates the cumulative distribution of a value."},
		{Text: "CURRENT", Description: "Refers to the current date, time, or user."},
		{Text: "CURRENT_CATALOG", Description: "Returns the current catalog name."},
		{Text: "CURRENT_DATE", Description: "Returns the current date."},
		{Text: "CURRENT_DEFAULT_TRANSFORM_GROUP", Description: "Returns the default transformation group."},
		{Text: "CURRENT_PATH", Description: "Returns the current search path."},
		{Text: "CURRENT_ROLE", Description: "Returns the current role name."},
		{Text: "CURRENT_ROW", Description: "Refers to the current row in a result set."},
		{Text: "CURRENT_SCHEMA", Description: "Returns the current schema name."},
		{Text: "CURRENT_TIME", Description: "Returns the current time."},
		{Text: "CURRENT_TIMESTAMP", Description: "Returns the current timestamp."},
		{Text: "CURRENT_TRANSFORM_GROUP_FOR_TYPE", Description: "Returns the current transformation group for a data type."},
		{Text: "CURRENT_USER", Description: "Returns the current user name."},
		{Text: "CURSOR", Description: "Represents a cursor or a result set."},
		{Text: "CURSOR_NAME", Description: "Returns the name of a cursor."},
		{Text: "CYCLE", Description: "Specifies a loop with cyclic behavior."},
		{Text: "DATA", Description: "Represents data stored in a database."},
		{Text: "DATABASE", Description: "Represents a database."},
		{Text: "DATE", Description: "Represents a date value."},
		{Text: "DATETIME", Description: "Represents a date and time value."},
		{Text: "DATETIME_DIFF", Description: "Calculates the difference between two date and time values."},
		{Text: "DATETIME_INTERVAL_CODE", Description: "Returns the code for a datetime interval."},
		{Text: "DATETIME_INTERVAL_PRECISION", Description: "Returns the precision for a datetime interval."},
		{Text: "DATE_DIFF", Description: "Calculates the difference between two date values."},
		{Text: "DATE_TRUNC", Description: "Truncates a date to a specified part."},
		{Text: "DAY", Description: "Represents a day in a date value."},
		{Text: "DAYS", Description: "Represents a duration in days."},
		{Text: "DEALLOCATE", Description: "Frees resources associated with a cursor."},
		{Text: "DEC", Description: "Represents a decimal data type."},
		{Text: "DECADE", Description: "Represents a decade in a date or time."},
		{Text: "DECIMAL", Description: "Represents a decimal data type."},
		{Text: "DECLARE", Description: "Defines a cursor or a variable."},
		{Text: "DEFAULT", Description: "Specifies a default value for a column or parameter."},
		{Text: "DEFAULTS", Description: "Specifies default options or settings."},
		{Text: "DEFERRABLE", Description: "Specifies a constraint that can be deferred."},
		{Text: "DEFERRED", Description: "Specifies a constraint that is deferred."},
		{Text: "DEFINE", Description: "Defines a macro or a constant."},
		{Text: "DEFINED", Description: "Indicates whether a value is defined or not."},
		{Text: "DEFINER", Description: "Specifies the creator or owner of an object."},
		{Text: "DEGREE", Description: "Represents the degree of an angle."},
		{Text: "DELETE", Description: "Deletes rows from a table or view."},
		{Text: "DENSE_RANK", Description: "Assigns a rank to rows within a result set."},
		{Text: "DEPTH", Description: "Represents the depth of an element in a hierarchy."},
		{Text: "DEREF", Description: "Dereferences a structured or user-defined type."},
		{Text: "DERIVED", Description: "Specifies a value derived from an expression."},
		{Text: "DESC", Description: "Specifies descending order in sorting."},
		{Text: "DESCRIBE", Description: "Describes the structure of a database object."},
		{Text: "DESCRIPTION", Description: "Represents a description or comment for an object."},
		{Text: "DESCRIPTOR", Description: "Describes the structure of a result set."},
		{Text: "DETERMINISTIC", Description: "Indicates a function that always produces the same result for the same inputs."},
		{Text: "DIAGNOSTICS", Description: "Returns information about the completion status of a statement."},
		{Text: "DISALLOW", Description: "Prohibits a specified action or value."},
		{Text: "DISCONNECT", Description: "Closes a connection to a database or network service."},
		{Text: "DISPATCH", Description: "Calls the appropriate function based on the data type."},
		{Text: "DISTINCT", Description: "Filters duplicate values from a result set."},
		{Text: "DOMAIN", Description: "Defines a data type with optional constraints."},
		{Text: "DOT", Description: "Specifies the concatenation of two strings."},
		{Text: "DOUBLE", Description: "Represents a double-precision floating-point data type."},
		{Text: "DOW", Description: "Represents the day of the week in a date value."},
		{Text: "DOY", Description: "Represents the day of the year in a date value."},
		{Text: "DROP", Description: "Removes a database object from the database."},
		{Text: "DYNAMIC", Description: "Specifies dynamic SQL or dynamic parameters."},
		{Text: "DYNAMIC_FUNCTION", Description: "Specifies the dynamic function invoked in a SQL statement."},
		{Text: "DYNAMIC_FUNCTION_CODE", Description: "Returns the code of the dynamic function."},
		{Text: "EACH", Description: "Applies a function to each element in a set."},
		{Text: "ELEMENT", Description: "Represents an element in a collection or array."},
		{Text: "ELSE", Description: "Defines an alternative branch in conditional logic."},
		{Text: "EMPTY", Description: "Specifies an empty result set or collection."},
		{Text: "ENCODING", Description: "Specifies the character encoding of a string."},
		{Text: "END", Description: "Ends a block of executable statements."},
		{Text: "END-EXEC", Description: "Marks the end of dynamic SQL."},
		{Text: "END_FRAME", Description: "Marks the end of a frame within a window function."},
		{Text: "END_PARTITION", Description: "Marks the end of a partition within a window function."},
		{Text: "EPOCH", Description: "Represents the number of seconds since January 1, 1970."},
		{Text: "EQUALS", Description: "Checks if two values are equal."},
		{Text: "ERROR", Description: "Represents an error or exception."},
		{Text: "ESCAPE", Description: "Specifies an escape character for special characters in strings."},
		{Text: "EVERY", Description: "Specifies a condition that applies to every element in a set."},
		{Text: "EXCEPT", Description: "Performs a set operation to return distinct rows from the left query that are not in the right query."},
		{Text: "EXCEPTION", Description: "Handles errors or exceptional conditions."},
		{Text: "EXCLUDE", Description: "Excludes specific elements from a group."},
		{Text: "EXCLUDING", Description: "Excludes specified elements from a set."},
		{Text: "EXEC", Description: "Executes a SQL statement or a stored procedure."},
		{Text: "EXECUTE", Description: "Executes a prepared statement."},
		{Text: "EXISTS", Description: "Checks if a subquery returns any rows."},
		{Text: "EXP", Description: "Calculates the exponential value of a number."},
		{Text: "EXPLAIN", Description: "Returns information about how a SQL statement will be executed."},
		{Text: "EXTEND", Description: "Adds new attributes or operations to a class."},
		{Text: "EXTERNAL", Description: "Specifies an external routine or file."},
		{Text: "EXTRACT", Description: "Retrieves parts of a date or time value."},
		{Text: "FALSE", Description: "Represents the Boolean value false."},
		{Text: "FETCH", Description: "Retrieves rows from a cursor or a result set."},
		{Text: "FILTER", Description: "Applies a filter to a result set."},
		{Text: "FINAL", Description: "Specifies a final method that cannot be overridden."},
		{Text: "FIRST", Description: "Returns the first element in a set."},
		{Text: "FIRST_VALUE", Description: "Returns the value of the first row in a window."},
		{Text: "FLOAT", Description: "Represents a single-precision floating-point data type."},
		{Text: "FLOOR", Description: "Returns the largest integer less than or equal to a number."},
		{Text: "FOLLOWING", Description: "Specifies the end of a window frame."},
		{Text: "FOR", Description: "Specifies the target or scope of an action."},
		{Text: "FOREIGN", Description: "Specifies a foreign key relationship."},
		{Text: "FORMAT", Description: "Specifies the format of a date or time value."},
		{Text: "FORTRAN", Description: "Indicates support for the Fortran programming language."},
		{Text: "FOUND", Description: "Indicates whether a cursor has found a row."},
		{Text: "FRAC_SECOND", Description: "Represents fractional seconds in a time value."},
		{Text: "FRAME_ROW", Description: "Specifies a boundary of a window frame."},
		{Text: "FREE", Description: "Frees resources used by a cursor."},
		{Text: "FRIDAY", Description: "Represents Friday as a day of the week."},
		{Text: "FROM", Description: "Specifies the source of data in a query."},
		{Text: "FULL", Description: "Specifies a full outer join of two tables."},
		{Text: "FUNCTION", Description: "Defines a user-defined function."},
		{Text: "FUSION", Description: "Specifies the merging of time periods in a temporal table."},
		{Text: "G", Description: "Represents the G programming language."},
		{Text: "GENERAL", Description: "Indicates a generic data type or condition."},
		{Text: "GENERATED", Description: "Specifies a generated column."},
		{Text: "GEOMETRY", Description: "Represents a geometric data type."},
		{Text: "GET", Description: "Retrieves the value of a variable or attribute."},
		{Text: "GLOBAL", Description: "Specifies global access or scope."},
		{Text: "GO", Description: "Marks the end of a batch of SQL statements."},
		{Text: "GOTO", Description: "Transfers control to a labeled statement."},
		{Text: "GRANT", Description: "Grants privileges or permissions to a user or role."},
		{Text: "GRANTED", Description: "Indicates a privilege that has been granted."},
		{Text: "GROUP", Description: "Groups rows based on a common value."},
		{Text: "GROUPING", Description: "Specifies a grouping operation in a GROUP BY clause."},
		{Text: "GROUPS", Description: "Specifies the number of groups in a window frame."},
		{Text: "GROUP_CONCAT", Description: "Concatenates strings from a group into a single string."},
		{Text: "HAVING", Description: "Filters groups in a GROUP BY clause."},
		{Text: "HIERARCHY", Description: "Represents a hierarchical relationship."},
		{Text: "HOLD", Description: "Preserves a lock on data until the end of the transaction."},
		{Text: "HOP", Description: "Specifies a hop size in a pattern match."},
		{Text: "HOUR", Description: "Represents an hour in a time value."},
		{Text: "HOURS", Description: "Represents a duration in hours."},
		{Text: "IDENTITY", Description: "Defines an auto-incrementing column."},
		{Text: "IGNORE", Description: "Ignores errors or duplicate rows in a query."},
		{Text: "ILIKE", Description: "Performs a case-insensitive pattern match."},
		{Text: "IMMEDIATE", Description: "Executes a statement without delay."},
		{Text: "IMMEDIATELY", Description: "Specifies immediate evaluation of an expression."},
		{Text: "IMPLEMENTATION", Description: "Specifies the implementation of a routine."},
		{Text: "IMPORT", Description: "Imports data from an external source."},
		{Text: "IN", Description: "Specifies a list of values or a subquery."},
		{Text: "INCLUDE", Description: "Includes specific elements in a set."},
		{Text: "INCLUDING", Description: "Includes specified elements in a set."},
		{Text: "INCREMENT", Description: "Increases a sequence or counter by a specific value."},
		{Text: "INDICATOR", Description: "Specifies a flag that indicates the status of a value."},
		{Text: "INITIAL", Description: "Specifies an initial value for an attribute."},
		{Text: "INITIALLY", Description: "Specifies the default time to start a transaction."},
		{Text: "INNER", Description: "Specifies an inner join of two tables."},
		{Text: "INOUT", Description: "Specifies a parameter that can be both input and output."},
		{Text: "INPUT", Description: "Specifies an input value or parameter."},
		{Text: "INSENSITIVE", Description: "Indicates case insensitivity."},
		{Text: "INSERT", Description: "Adds rows to a table or view."},
		{Text: "INSTANCE", Description: "Represents an instance of a class."},
		{Text: "INSTANTIABLE", Description: "Indicates that a user-defined type can be instantiated."},
		{Text: "INT", Description: "Represents an integer data type."},
		{Text: "INTEGER", Description: "Represents an integer data type."},
		{Text: "INTERSECT", Description: "Performs a set operation to return rows common to both queries."},
		{Text: "INTERSECTION", Description: "Performs a set operation to return rows common to both queries."},
		{Text: "INTERVAL", Description: "Represents a time interval."},
		{Text: "INTO", Description: "Specifies the destination of data in an INSERT statement."},
		{Text: "INVOKER", Description: "Specifies the user who invokes a routine."},
		{Text: "IS", Description: "Checks the truth value or equality of two values."},
		{Text: "ISODOW", Description: "Represents the ISO day of the week in a date value."},
		{Text: "ISOLATION", Description: "Specifies the level of transaction isolation."},
		{Text: "ISOYEAR", Description: "Represents the ISO year in a date value."},
		{Text: "JAVA", Description: "Indicates support for the Java programming language."},
		{Text: "JOIN", Description: "Combines rows from two or more tables."},
		{Text: "JSON", Description: "Represents a JSON data type."},
		{Text: "JSON_ARRAY", Description: "Represents a JSON array."},
		{Text: "JSON_ARRAYAGG", Description: "Aggregates elements into a JSON array."},
		{Text: "JSON_EXISTS", Description: "Checks if a JSON value exists."},
		{Text: "JSON_OBJECT", Description: "Represents a JSON object."},
		{Text: "JSON_OBJECTAGG", Description: "Aggregates elements into a JSON object."},
		{Text: "JSON_QUERY", Description: "Extracts a JSON value."},
		{Text: "JSON_VALUE", Description: "Extracts a JSON value as a scalar."},
		{Text: "K", Description: "Represents the K programming language."},
		{Text: "KEY", Description: "Represents a key or unique identifier."},
		{Text: "KEY_MEMBER", Description: "Represents a member of a key."},
		{Text: "KEY_TYPE", Description: "Represents the type of a key."},
		{Text: "LABEL", Description: "Names a statement or block of code."},
		{Text: "LAG", Description: "Accesses a value from a previous row in a result set."},
		{Text: "LANGUAGE", Description: "Specifies the language used in a routine."},
		{Text: "LARGE", Description: "Indicates a large object data type."},
		{Text: "LAST", Description: "Returns the last element in a set."},
		{Text: "LAST_VALUE", Description: "Returns the value of the last row in a window."},
		{Text: "LATERAL", Description: "Specifies a lateral join of two tables."},
		{Text: "LEAD", Description: "Accesses a value from a following row in a result set."},
		{Text: "LEADING", Description: "Specifies the characters trimmed from a string."},
		{Text: "LEFT", Description: "Specifies a left outer join of two tables."},
		{Text: "LENGTH", Description: "Returns the number of bytes in a string."},
		{Text: "LEVEL", Description: "Represents the level of an element in a hierarchy."},
		{Text: "LIBRARY", Description: "Specifies an external library or resource."},
		{Text: "LIKE", Description: "Performs a case-sensitive pattern match."},
		{Text: "LIKE_REGEX", Description: "Performs a case-sensitive pattern match with regex."},
		{Text: "LIMIT", Description: "Limits the number of rows returned in a result set."},
		{Text: "LN", Description: "Returns the natural logarithm of a number."},
		{Text: "LOCAL", Description: "Specifies local access or scope."},
		{Text: "LOCALTIME", Description: "Returns the current time in the local time zone."},
		{Text: "LOCALTIMESTAMP", Description: "Returns the current timestamp in the local time zone."},
		{Text: "LOCATOR", Description: "Represents a locator or reference to a large object."},
		{Text: "LOWER", Description: "Converts a string to lowercase."},
		{Text: "M", Description: "Represents the M programming language."},
		{Text: "MAP", Description: "Represents a key-value pair or mapping."},
		{Text: "MATCH", Description: "Performs a full-text search or pattern match."},
		{Text: "MATCHED", Description: "Indicates whether a row is matched in a MERGE statement."},
		{Text: "MATCHES", Description: "Performs a regular expression pattern match."},
		{Text: "MATCH_NUMBER", Description: "Returns the occurrence number in a pattern match."},
		{Text: "MATCH_RECOGNIZE", Description: "Performs pattern recognition in a sequence of rows."},
		{Text: "MAX", Description: "Returns the maximum value in a set."},
		{Text: "MAXVALUE", Description: "Specifies the maximum value for a column or sequence."},
		{Text: "MEASURES", Description: "Defines measures in a cube or data cube operation."},
		{Text: "MEMBER", Description: "Represents a member in a set or dimension."},
		{Text: "MERGE", Description: "Performs an insert, update, or delete based on a condition."},
		{Text: "MESSAGE_LENGTH", Description: "Returns the length of a message."},
		{Text: "MESSAGE_OCTET_LENGTH", Description: "Returns the length of a message in octets."},
		{Text: "MESSAGE_TEXT", Description: "Returns the text of a message."},
		{Text: "METHOD", Description: "Represents a method or operation."},
		{Text: "MICROSECOND", Description: "Represents a microsecond in a time value."},
		{Text: "MILLENNIUM", Description: "Represents a millennium in a date or time."},
		{Text: "MILLISECOND", Description: "Represents a millisecond in a time value."},
		{Text: "MIN", Description: "Returns the minimum value in a set."},
		{Text: "MINUS", Description: "Performs a set operation to return rows in the left query that are not in the right query."},
		{Text: "MINUTE", Description: "Represents a minute in a time value."},
		{Text: "MINUTES", Description: "Represents a duration in minutes."},
		{Text: "MINVALUE", Description: "Specifies the minimum value for a column or sequence."},
		{Text: "MOD", Description: "Calculates the remainder of a division."},
		{Text: "MODIFIES", Description: "Specifies a variable that is modified in a routine."},
		{Text: "MODULE", Description: "Represents a module or component."},
		{Text: "MONDAY", Description: "Represents Monday as a day of the week."},
		{Text: "MONTH", Description: "Represents a month in a date value."},
		{Text: "MONTHS", Description: "Represents a duration in months."},
		{Text: "MORE", Description: "Specifies additional elements or items."},
		{Text: "MULTISET", Description: "Represents a multiset or collection of values."},
		{Text: "MUMPS", Description: "Indicates support for the MUMPS programming language."},
		{Text: "NAME", Description: "Represents a name or identifier."},
		{Text: "NAMES", Description: "Specifies the character set or encoding names."},
		{Text: "NANOSECOND", Description: "Represents a nanosecond in a time value."},
		{Text: "NATIONAL", Description: "Specifies a national character string."},
		{Text: "NATURAL", Description: "Specifies natural join of two tables."},
		{Text: "NCHAR", Description: "Represents a fixed-length national character string."},
		{Text: "NCLOB", Description: "Represents a large fixed-length national character string."},
		{Text: "NESTING", Description: "Specifies the nesting level of a result set."},
		{Text: "NEW", Description: "Refers to new values in an INSERT or UPDATE trigger."},
		{Text: "NEXT", Description: "Returns the next value from a sequence."},
		{Text: "NO", Description: "Specifies negation or the absence of a condition."},
		{Text: "NONE", Description: "Indicates the absence of a value or condition."},
		{Text: "NORMALIZE", Description: "Converts a string to normalized form."},
		{Text: "NORMALIZED", Description: "Specifies normalization or standardization."},
		{Text: "NOT", Description: "Negates a Boolean expression or condition."},
		{Text: "NTH_VALUE", Description: "Returns the value of the nth row in a result set."},
		{Text: "NTILE", Description: "Calculates the tile number for each row in a result set."},
		{Text: "NULL", Description: "Represents the absence of a value or unknown."},
		{Text: "NULLABLE", Description: "Specifies whether a column or parameter allows NULL values."},
		{Text: "NULLIF", Description: "Returns NULL if two expressions are equal."},
		{Text: "NULLS", Description: "Specifies the ordering of NULL values in a result set."},
		{Text: "NUMBER", Description: "Represents a numeric data type."},
		{Text: "NUMERIC", Description: "Represents a numeric data type."},
		{Text: "OBJECT", Description: "Represents an object or instance."},
		{Text: "OCCURRENCES_REGEX", Description: "Returns the number of occurrences of a regex pattern."},
		{Text: "OCTETS", Description: "Represents the number of bytes in a string."},
		{Text: "OCTET_LENGTH", Description: "Returns the number of bytes in a string."},
		{Text: "OF", Description: "Specifies the type or data type of an object or attribute."},
		{Text: "OFFSET", Description: "Specifies the starting point or position in a result set."},
		{Text: "OLD", Description: "Refers to old values in a DELETE or UPDATE trigger."},
		{Text: "OMIT", Description: "Excludes specific elements from a set."},
		{Text: "ON", Description: "Specifies a condition or event for a trigger or join."},
		{Text: "ONE", Description: "Specifies that exactly one row or element is expected."},
		{Text: "ONLY", Description: "Specifies a single occurrence or exclusive option."},
		{Text: "OPEN", Description: "Opens a cursor or a file."},
		{Text: "OPTION", Description: "Specifies options or settings."},
		{Text: "OPTIONS", Description: "Specifies options or settings."},
		{Text: "OR", Description: "A logical operator representing a disjunction (OR)."},
		{Text: "ORDER", Description: "Specifies the sorting of rows in a result set."},
		{Text: "ORDERING", Description: "Specifies the ordering of a set or sequence."},
		{Text: "ORDINALITY", Description: "Represents the ordinal position of an element in a list."},
		{Text: "OTHERS", Description: "Refers to all other values or cases."},
		{Text: "OUT", Description: "Specifies a parameter that returns a value."},
		{Text: "OUTER", Description: "Specifies an outer join of two tables."},
		{Text: "OUTPUT", Description: "Specifies an output value or parameter."},
		{Text: "OVER", Description: "Specifies a window or partition for a window function."},
		{Text: "OVERLAPS", Description: "Checks if two time intervals overlap."},
		{Text: "OVERLAY", Description: "Replaces part of a string with another string."},
		{Text: "OVERRIDING", Description: "Specifies the behavior of an overridden method."},
		{Text: "PAD", Description: "Pads a string with specific characters."},
		{Text: "PARAMETER", Description: "Represents a parameter or input to a routine."},
		{Text: "PARAMETER_MODE", Description: "Specifies the mode of a parameter."},
		{Text: "PARAMETER_NAME", Description: "Returns the name of a parameter."},
		{Text: "PARAMETER_ORDINAL_POSITION", Description: "Returns the ordinal position of a parameter."},
		{Text: "PARAMETER_SPECIFIC_CATALOG", Description: "Returns the catalog of a parameter."},
		{Text: "PARAMETER_SPECIFIC_NAME", Description: "Returns the name of a parameter."},
		{Text: "PARAMETER_SPECIFIC_SCHEMA", Description: "Returns the schema of a parameter."},
		{Text: "PARTIAL", Description: "Specifies partial matching or approximation."},
		{Text: "PARTITION", Description: "Divides a result set into partitions."},
		{Text: "PASCAL", Description: "Indicates support for the Pascal programming language."},
		{Text: "PASSING", Description: "Specifies values passed to a window function."},
		{Text: "PASSTHROUGH", Description: "Passes a value through a routine without modification."},
		{Text: "PAST", Description: "Specifies a point or duration in the past."},
		{Text: "PATH", Description: "Represents a path or sequence of elements."},
		{Text: "PATTERN", Description: "Specifies a pattern in a pattern matching operation."},
		{Text: "PER", Description: "Specifies a frequency or rate of occurrence."},
		{Text: "PERCENT", Description: "Represents a percentage value."},
		{Text: "PERCENTILE_CONT", Description: "Calculates a continuous percentile."},
		{Text: "PERCENTILE_DISC", Description: "Calculates a discrete percentile."},
		{Text: "PERCENT_RANK", Description: "Calculates the percentile rank of a value."},
		{Text: "PERIOD", Description: "Represents a period or interval of time."},
		{Text: "PERMUTE", Description: "Permute elements within a set."},
		{Text: "PIVOT", Description: "Transforms rows into columns in a result set."},
		{Text: "PLACING", Description: "Specifies the placement or ordering of elements."},
		{Text: "PLAN", Description: "Describes the execution plan of a query."},
		{Text: "PLI", Description: "Indicates support for the PL/I programming language."},
		{Text: "PORTION", Description: "Specifies a part or segment of a value."},
		{Text: "POSITION", Description: "Finds the position of a substring in a string."},
		{Text: "POSITION_REGEX", Description: "Finds the position of a regex pattern in a string."},
		{Text: "POWER", Description: "Calculates the power of a number."},
		{Text: "PRECEDES", Description: "Checks if a value precedes another value."},
		{Text: "PRECEDING", Description: "Specifies the start of a window frame."},
		{Text: "PRECISION", Description: "Specifies the precision of a numeric data type."},
		{Text: "PREPARE", Description: "Prepares a statement for execution."},
		{Text: "PRESERVE", Description: "Preserves existing values or settings."},
		{Text: "PREV", Description: "Refers to the previous value in a window or result set."},
		{Text: "PRIMARY", Description: "Specifies a primary key constraint."},
		{Text: "PRIOR", Description: "Refers to the previous row in a result set."},
		{Text: "PRIVILEGES", Description: "Specifies access rights or permissions."},
		{Text: "PROCEDURE", Description: "Defines a stored procedure."},
		{Text: "PUBLIC", Description: "Specifies public access or visibility."},
		{Text: "QUALIFY", Description: "Filters rows based on a condition after grouping."},
		{Text: "QUARTER", Description: "Represents a quarter in a date value."},
		{Text: "QUARTERS", Description: "Represents a duration in quarters."},
		{Text: "RANGE", Description: "Specifies a range of values in a window frame."},
		{Text: "RANK", Description: "Assigns a rank to rows within a result set."},
		{Text: "READ", Description: "Specifies read access or permission."},
		{Text: "READS", Description: "Specifies the number of read operations."},
		{Text: "REAL", Description: "Represents a real data type."},
		{Text: "RECURSIVE", Description: "Specifies a recursive common table expression."},
		{Text: "REF", Description: "Represents a reference to an object or value."},
		{Text: "REFERENCES", Description: "Specifies a foreign key relationship."},
		{Text: "REFERENCING", Description: "Specifies the names of old and new values in a trigger."},
		{Text: "REGR_AVGX", Description: "Calculates the average of the independent variable."},
		{Text: "REGR_AVGY", Description: "Calculates the average of the dependent variable."},
		{Text: "REGR_COUNT", Description: "Counts the number of non-null pairs in a regression."},
		{Text: "REGR_INTERCEPT", Description: "Calculates the y-intercept of a regression line."},
		{Text: "REGR_R2", Description: "Calculates the coefficient of determination in a regression."},
		{Text: "REGR_SLOPE", Description: "Calculates the slope of a regression line."},
		{Text: "REGR_SXX", Description: "Calculates the sum of squares of the independent variable."},
		{Text: "REGR_SXY", Description: "Calculates the sum of products of the independent and dependent variables."},
		{Text: "REGR_SYY", Description: "Calculates the sum of squares of the dependent variable."},
		{Text: "RELATIVE", Description: "Specifies the ordering of rows in a result set."},
		{Text: "RELEASE", Description: "Releases resources held by a SAVEPOINT."},
		{Text: "REPEATABLE", Description: "Specifies repeatable read isolation level."},
		{Text: "REPLACE", Description: "Replaces occurrences of a substring in a string."},
		{Text: "RESET", Description: "Resets the value of a sequence."},
		{Text: "RESPECT", Description: "Specifies respect for ordering or precedence."},
		{Text: "RESTART", Description: "Restarts a sequence with a specified value."},
		{Text: "RESTRICT", Description: "Restricts actions or operations."},
		{Text: "RESULT", Description: "Specifies the result of a function or expression."},
		{Text: "RETURN", Description: "Exits a function or stored procedure."},
		{Text: "RETURNED_CARDINALITY", Description: "Returns the cardinality of a result."},
		{Text: "RETURNED_LENGTH", Description: "Returns the length of a result."},
		{Text: "RETURNED_OCTET_LENGTH", Description: "Returns the length of a result in octets."},
		{Text: "RETURNED_SQLSTATE", Description: "Returns the SQLSTATE of a result."},
		{Text: "RETURNING", Description: "Specifies the result set of a DML statement."},
		{Text: "RETURNS", Description: "Specifies the return type of a function or procedure."},
		{Text: "REVOKE", Description: "Revokes privileges or permissions from a user or role."},
		{Text: "RIGHT", Description: "Specifies a right outer join of two tables."},
		{Text: "RLIKE", Description: "Performs a regular expression pattern match."},
		{Text: "ROLE", Description: "Represents a role or user group."},
		{Text: "ROLLBACK", Description: "Undoes changes made during a transaction."},
		{Text: "ROLLUP", Description: "Generates groups with multiple levels of aggregation."},
		{Text: "ROUTINE", Description: "Represents a routine or procedure."},
		{Text: "ROUTINE_CATALOG", Description: "Returns the catalog of a routine."},
		{Text: "ROUTINE_NAME", Description: "Returns the name of a routine."},
		{Text: "ROUTINE_SCHEMA", Description: "Returns the schema of a routine."},
		{Text: "ROW", Description: "Represents a row of data in a result set."},
		{Text: "ROWS", Description: "Specifies the number of rows affected or returned."},
		{Text: "ROW_COUNT", Description: "Returns the number of rows affected by a statement."},
		{Text: "ROW_NUMBER", Description: "Assigns a unique number to each row in a result set."},
		{Text: "RUNNING", Description: "Calculates a running total in a result set."},
		{Text: "SATURDAY", Description: "Represents Saturday as a day of the week."},
		{Text: "SAVEPOINT", Description: "Defines a point in a transaction to which you can later roll back."},
		{Text: "SCALAR", Description: "Specifies a scalar function or expression."},
		{Text: "SCALE", Description: "Specifies the scale of a numeric data type."},
		{Text: "SCHEMA", Description: "Represents a schema or namespace."},
		{Text: "SCHEMA_NAME", Description: "Returns the name of a schema."},
		{Text: "SCOPE", Description: "Specifies the visibility of a variable."},
		{Text: "SCOPE_CATALOGS", Description: "Returns the catalog name used to determine scope."},
		{Text: "SCOPE_NAME", Description: "Returns the name used to determine scope."},
		{Text: "SCOPE_SCHEMA", Description: "Returns the schema name used to determine scope."},
		{Text: "SCROLL", Description: "Specifies scrollable or cursor-like behavior."},
		{Text: "SEARCH", Description: "Finds a substring in a string."},
		{Text: "SECOND", Description: "Represents a second in a time value."},
		{Text: "SECONDS", Description: "Represents a duration in seconds."},
		{Text: "SECTION", Description: "Specifies a section or portion of code."},
		{Text: "SECURITY", Description: "Specifies security settings or policies."},
		{Text: "SEEK", Description: "Seeks a specific position within a file or data."},
		{Text: "SELECT", Description: "Retrieves data from a database table."},
		{Text: "SELF", Description: "Refers to the current object or instance."},
		{Text: "SENSITIVE", Description: "Specifies sensitive case or data handling."},
		{Text: "SEPARATOR", Description: "Specifies a separator character or string."},
		{Text: "SEQUENCE", Description: "Represents a sequence generator."},
		{Text: "SERIALIZABLE", Description: "Specifies serializable isolation level."},
		{Text: "SERVER", Description: "Represents a server or database instance."},
		{Text: "SERVER_NAME", Description: "Returns the name of a server or database instance."},
		{Text: "SESSION", Description: "Represents a session or connection."},
		{Text: "SESSION_USER", Description: "Returns the user associated with a session."},
		{Text: "SET", Description: "Assigns values to variables or options."},
		{Text: "SETS", Description: "Specifies the set of values in a result set."},
		{Text: "SHOW", Description: "Displays information or settings."},
		{Text: "SIMILAR", Description: "Performs a similarity match with a pattern."},
		{Text: "SIMPLE", Description: "Specifies simple matching or comparison."},
		{Text: "SIZE", Description: "Returns the size or cardinality of a set."},
		{Text: "SKIP", Description: "Skips a specified number of elements in a result set."},
		{Text: "SMALLINT", Description: "Represents a small integer data type."},
		{Text: "SOME", Description: "Specifies that some condition must be true."},
		{Text: "SOURCE", Description: "Represents the source of data in a query or operation."},
		{Text: "SPACE", Description: "Returns the number of spaces in a string."},
		{Text: "SPECIFIC", Description: "Refers to a specific routine or method."},
		{Text: "SPECIFICTYPE", Description: "Specifies the specific data type of a column."},
		{Text: "SPECIFIC_NAME", Description: "Returns the name of a specific routine."},
		{Text: "SQL", Description: "Indicates SQL-specific syntax or functionality."},
		{Text: "SQLEXCEPTION", Description: "Represents an exception in SQL."},
		{Text: "SQLSTATE", Description: "Returns the SQLSTATE of an error."},
		{Text: "SQLWARNING", Description: "Represents a warning in SQL."},
		{Text: "SQL_BIGINT", Description: "Represents a 64-bit integer data type."},
		{Text: "SQL_BINARY", Description: "Represents a binary data type."},
		{Text: "SQL_BIT", Description: "Represents a Boolean data type."},
		{Text: "SQL_BLOB", Description: "Represents a binary large object data type."},
		{Text: "SQL_BOOLEAN", Description: "Represents a Boolean data type."},
		{Text: "SQL_CHAR", Description: "Represents a fixed-length character data type."},
		{Text: "SQL_CLOB", Description: "Represents a character large object data type."},
		{Text: "SQL_DATE", Description: "Represents a date data type."},
		{Text: "SQL_DECIMAL", Description: "Represents a fixed-point decimal data type."},
		{Text: "SQL_DOUBLE", Description: "Represents a double-precision floating-point data type."},
		{Text: "SQL_FLOAT", Description: "Represents a floating-point data type."},
		{Text: "SQL_INTEGER", Description: "Represents a 32-bit integer data type."},
		{Text: "SQL_INTERVAL_DAY", Description: "Represents a day interval data type."},
		{Text: "SQL_INTERVAL_DAY_TO_HOUR", Description: "Represents a day to hour interval data type."},
		{Text: "SQL_INTERVAL_DAY_TO_MINUTE", Description: "Represents a day to minute interval data type."},
		{Text: "SQL_INTERVAL_DAY_TO_SECOND", Description: "Represents a day to second interval data type."},
		{Text: "SQL_INTERVAL_HOUR", Description: "Represents an hour interval data type."},
		{Text: "SQL_INTERVAL_HOUR_TO_MINUTE", Description: "Represents an hour to minute interval data type."},
		{Text: "SQL_INTERVAL_HOUR_TO_SECOND", Description: "Represents an hour to second interval data type."},
		{Text: "SQL_INTERVAL_MINUTE", Description: "Represents a minute interval data type."},
		{Text: "SQL_INTERVAL_MINUTE_TO_SECOND", Description: "Represents a minute to second interval data type."},
		{Text: "SQL_INTERVAL_MONTH", Description: "Represents a month interval data type."},
		{Text: "SQL_INTERVAL_SECOND", Description: "Represents a second interval data type."},
		{Text: "SQL_INTERVAL_YEAR", Description: "Represents a year interval data type."},
		{Text: "SQL_INTERVAL_YEAR_TO_MONTH", Description: "Represents a year to month interval data type."},
		{Text: "SQL_LONGVARBINARY", Description: "Represents a variable-length binary data type."},
		{Text: "SQL_LONGVARCHAR", Description: "Represents a variable-length character data type."},
		{Text: "SQL_LONGVARNCHAR", Description: "Represents a variable-length national character data type."},
		{Text: "SQL_NCHAR", Description: "Represents a fixed-length national character data type."},
		{Text: "SQL_NCLOB", Description: "Represents a large fixed-length national character data type."},
		{Text: "SQL_NUMERIC", Description: "Represents a fixed-point decimal data type."},
		{Text: "SQL_NVARCHAR", Description: "Represents a variable-length national character data type."},
		{Text: "SQL_REAL", Description: "Represents a single-precision floating-point data type."},
		{Text: "SQL_SMALLINT", Description: "Represents a small integer data type."},
		{Text: "SQL_TIME", Description: "Represents a time data type."},
		{Text: "SQL_TIMESTAMP", Description: "Represents a timestamp data type."},
		{Text: "SQL_TINYINT", Description: "Represents a tiny integer data type."},
		{Text: "SQL_TSI_DAY", Description: "Represents a day interval data type."},
		{Text: "SQL_TSI_FRAC_SECOND", Description: "Represents a fractional second interval data type."},
		{Text: "SQL_TSI_HOUR", Description: "Represents an hour interval data type."},
		{Text: "SQL_TSI_MICROSECOND", Description: "Represents a microsecond interval data type."},
		{Text: "SQL_TSI_MINUTE", Description: "Represents a minute interval data type."},
		{Text: "SQL_TSI_MONTH", Description: "Represents a month interval data type."},
		{Text: "SQL_TSI_QUARTER", Description: "Represents a quarter interval data type."},
		{Text: "SQL_TSI_SECOND", Description: "Represents a second interval data type."},
		{Text: "SQL_TSI_WEEK", Description: "Represents a week interval data type."},
		{Text: "SQL_TSI_YEAR", Description: "Represents a year interval data type."},
		{Text: "SQL_VARBINARY", Description: "Represents a variable-length binary data type."},
		{Text: "SQL_VARCHAR", Description: "Represents a variable-length character data type."},
		{Text: "SQRT", Description: "Calculates the square root of a number."},
		{Text: "START", Description: "Specifies the beginning or starting point."},
		{Text: "STATE", Description: "Represents the state or status of an object."},
		{Text: "STATEMENT", Description: "Represents a SQL statement or command."},
		{Text: "STATIC", Description: "Specifies static storage or behavior."},
		{Text: "STDDEV_POP", Description: "Calculates the population standard deviation."},
		{Text: "STDDEV_SAMP", Description: "Calculates the sample standard deviation."},
		{Text: "STREAM", Description: "Specifies a stream of data or events."},
		{Text: "STRING_AGG", Description: "Aggregates strings into a single string."},
		{Text: "STRUCTURE", Description: "Specifies the structure or layout of data."},
		{Text: "STYLE", Description: "Specifies the format style of a date or time value."},
		{Text: "SUBCLASS_ORIGIN", Description: "Specifies the origin of a subclass."},
		{Text: "SUBMULTISET", Description: "Represents a submultiset or subset of a set."},
		{Text: "SUBSET", Description: "Specifies a subset or proper subset relationship."},
		{Text: "SUBSTITUTE", Description: "Substitutes one value with another in a set."},
		{Text: "SUBSTRING", Description: "Extracts a substring from a string."},
		{Text: "SUBSTRING_REGEX", Description: "Extracts a substring using a regex pattern."},
		{Text: "SUCCEEDS", Description: "Checks if a value succeeds another value."},
		{Text: "SUM", Description: "Calculates the sum of values in a set."},
		{Text: "SUNDAY", Description: "Represents Sunday as a day of the week."},
		{Text: "SYMMETRIC", Description: "Specifies symmetric encryption or behavior."},
		{Text: "SYSTEM", Description: "Represents system settings or properties."},
		{Text: "SYSTEM_TIME", Description: "Represents the system time period of a temporal table."},
		{Text: "SYSTEM_USER", Description: "Returns the system user associated with a session."},
		{Text: "TABLE", Description: "Represents a database table or object."},
		{Text: "TABLESAMPLE", Description: "Selects a sample of rows from a table."},
		{Text: "TABLE_NAME", Description: "Returns the name of a table."},
		{Text: "TEMPORARY", Description: "Specifies a temporary object or table."},
		{Text: "THEN", Description: "Specifies the result or action when a condition is true."},
		{Text: "THURSDAY", Description: "Represents Thursday as a day of the week."},
		{Text: "TIES", Description: "Specifies that tied rows receive the same rank."},
		{Text: "TIME", Description: "Represents a time data type."},
		{Text: "TIMESTAMP", Description: "Represents a timestamp data type."},
		{Text: "TIMESTAMPADD", Description: "Adds an interval to a timestamp."},
		{Text: "TIMESTAMPDIFF", Description: "Calculates the difference between two timestamps."},
		{Text: "TIMESTAMP_DIFF", Description: "Calculates the difference between two timestamps."},
		{Text: "TIMESTAMP_TRUNC", Description: "Truncates a timestamp to a specified unit."},
		{Text: "TIMEZONE_HOUR", Description: "Returns the time zone offset in hours."},
		{Text: "TIMEZONE_MINUTE", Description: "Returns the time zone offset in minutes."},
		{Text: "TIME_DIFF", Description: "Calculates the difference between two times."},
		{Text: "TIME_TRUNC", Description: "Truncates a time to a specified unit."},
		{Text: "TINYINT", Description: "Represents a tiny integer data type."},
		{Text: "TO", Description: "Specifies the target or destination of a conversion."},
		{Text: "TOP_LEVEL_COUNT", Description: "Counts the number of top-level elements in a JSON document."},
		{Text: "TRAILING", Description: "Trims characters from the end of a string."},
		{Text: "TRANSACTION", Description: "Represents a database transaction."},
		{Text: "TRANSACTIONS_ACTIVE", Description: "Returns the number of active transactions."},
		{Text: "TRANSACTIONS_COMMITTED", Description: "Returns the number of committed transactions."},
		{Text: "TRANSACTIONS_ROLLED_BACK", Description: "Returns the number of rolled back transactions."},
		{Text: "TRANSFORM", Description: "Performs data transformation or conversion."},
		{Text: "TRANSFORMS", Description: "Specifies a list of data transformations."},
		{Text: "TRANSLATE", Description: "Replaces characters in a string."},
		{Text: "TRANSLATE_REGEX", Description: "Replaces characters using a regex pattern in a string."},
		{Text: "TRANSLATION", Description: "Specifies the translation of a value or text."},
		{Text: "TREAT", Description: "Casts or converts a value to a specific data type."},
		{Text: "TRIGGER", Description: "Specifies a trigger or event handler."},
		{Text: "TRIGGER_CATALOG", Description: "Returns the catalog of a trigger."},
		{Text: "TRIGGER_NAME", Description: "Returns the name of a trigger."},
		{Text: "TRIGGER_SCHEMA", Description: "Returns the schema of a trigger."},
		{Text: "TRIM", Description: "Trims characters from the beginning and end of a string."},
		{Text: "TRIM_ARRAY", Description: "Trims null values from an array."},
		{Text: "TRUE", Description: "Represents the Boolean value TRUE."},
		{Text: "TRUNCATE", Description: "Truncates a numeric value to an integer."},
		{Text: "TUESDAY", Description: "Represents Tuesday as a day of the week."},
		{Text: "TUMBLE", Description: "Generates fixed-sized, non-overlapping time intervals."},
		{Text: "TYPE", Description: "Represents a data type or object type."},
		{Text: "UESCAPE", Description: "Specifies Unicode escape characters in a string."},
		{Text: "UNBOUNDED", Description: "Specifies an unbounded or infinite value."},
		{Text: "UNCOMMITTED", Description: "Specifies read uncommitted isolation level."},
		{Text: "UNCONDITIONAL", Description: "Specifies unconditional execution or behavior."},
		{Text: "UNDER", Description: "Specifies a containment or hierarchy relationship."},
		{Text: "UNION", Description: "Performs a set operation to combine result sets."},
		{Text: "UNIQUE", Description: "Specifies a unique constraint on a column."},
		{Text: "UNKNOWN", Description: "Represents an unknown or unspecified value."},
		{Text: "UNNAMED", Description: "Specifies an unnamed object or element."},
		{Text: "UNNEST", Description: "Expands an array into a table of rows."},
		{Text: "UNPIVOT", Description: "Transforms columns into rows in a result set."},
		{Text: "UPDATE", Description: "Modifies data in a database table."},
		{Text: "UPPER", Description: "Converts a string to uppercase."},
		{Text: "UPSERT", Description: "Performs an update or insert if a row exists or not."},
		{Text: "USAGE", Description: "Specifies usage or access permissions."},
		{Text: "USER", Description: "Represents a user or account."},
		{Text: "USER_DEFINED_TYPE_CATALOG", Description: "Returns the catalog of a user-defined type."},
		{Text: "USER_DEFINED_TYPE_CODE", Description: "Returns the code of a user-defined type."},
		{Text: "USER_DEFINED_TYPE_NAME", Description: "Returns the name of a user-defined type."},
		{Text: "USER_DEFINED_TYPE_SCHEMA", Description: "Returns the schema of a user-defined type."},
		{Text: "USING", Description: "Specifies a USING clause in a join or merge."},
		{Text: "UTF16", Description: "Specifies the UTF-16 character encoding."},
		{Text: "UTF32", Description: "Specifies the UTF-32 character encoding."},
		{Text: "UTF8", Description: "Specifies the UTF-8 character encoding."},
		{Text: "VALUE", Description: "Represents a value or constant."},
		{Text: "VALUES", Description: "Specifies a list of values."},
		{Text: "VALUE_OF", Description: "Returns the value of an XML element."},
		{Text: "VARBINARY", Description: "Represents a variable-length binary data type."},
		{Text: "VARCHAR", Description: "Represents a variable-length character data type."},
		{Text: "VARYING", Description: "Specifies varying length or behavior."},
		{Text: "VAR_POP", Description: "Calculates the population variance."},
		{Text: "VAR_SAMP", Description: "Calculates the sample variance."},
		{Text: "VERSION", Description: "Represents a version or release number."},
		{Text: "VERSIONING", Description: "Specifies temporal versioning or history tracking."},
		{Text: "VIEW", Description: "Represents a database view."},
		{Text: "WEDNESDAY", Description: "Represents Wednesday as a day of the week."},
		{Text: "WEEK", Description: "Represents a week in a date value."},
		{Text: "WEEKS", Description: "Represents a duration in weeks."},
		{Text: "WHEN", Description: "Specifies a condition or case in a CASE statement."},
		{Text: "WHENEVER", Description: "Specifies an action to be taken when an SQL exception occurs."},
		{Text: "WHERE", Description: "Filters rows in a result set based on a condition."},
		{Text: "WIDTH_BUCKET", Description: "Calculates the bucket number for a value in a specified range."},
		{Text: "WINDOW", Description: "Specifies a window or frame for a window function."},
		{Text: "WITH", Description: "Specifies optional clauses or subqueries."},
		{Text: "WITHIN", Description: "Specifies a distance or range within a location."},
		{Text: "WITHOUT", Description: "Specifies optional components or elements."},
		{Text: "WORK", Description: "Specifies transaction work or context."},
		{Text: "WRAPPER", Description: "Represents a wrapper or interface."},
		{Text: "WRITE", Description: "Specifies write access or permission."},
		{Text: "XML", Description: "Represents XML data or documents."},
		{Text: "YEAR", Description: "Represents a year in a date value."},
		{Text: "YEARS", Description: "Represents a duration in years."},
		{Text: "ZONE", Description: "Specifies a time zone offset or region."},

	}

    return prompt.FilterHasPrefix(suggestions, input, true)
}

