// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	common.proto
	requests.proto
	responses.proto

It has these top-level messages:
	ConnectionProperties
	StatementHandle
	Signature
	ColumnMetaData
	AvaticaType
	AvaticaParameter
	CursorFactory
	Frame
	Row
	DatabaseProperty
	WireMessage
	ColumnValue
	TypedValue
	MetaDataOperationArgument
	QueryState
	CatalogsRequest
	DatabasePropertyRequest
	SchemasRequest
	TablesRequest
	TableTypesRequest
	ColumnsRequest
	TypeInfoRequest
	PrepareAndExecuteRequest
	PrepareRequest
	FetchRequest
	CreateStatementRequest
	CloseStatementRequest
	OpenConnectionRequest
	CloseConnectionRequest
	ConnectionSyncRequest
	ExecuteRequest
	SyncResultsRequest
	CommitRequest
	RollbackRequest
	PrepareAndExecuteBatchRequest
	UpdateBatch
	ExecuteBatchRequest
	ResultSetResponse
	ExecuteResponse
	PrepareResponse
	FetchResponse
	CreateStatementResponse
	CloseStatementResponse
	OpenConnectionResponse
	CloseConnectionResponse
	ConnectionSyncResponse
	DatabasePropertyElement
	DatabasePropertyResponse
	ErrorResponse
	SyncResultsResponse
	RpcMetadata
	CommitResponse
	RollbackResponse
	ExecuteBatchResponse
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Has to be consistent with Meta.StatementType
type StatementType int32

const (
	StatementType_SELECT    StatementType = 0
	StatementType_INSERT    StatementType = 1
	StatementType_UPDATE    StatementType = 2
	StatementType_DELETE    StatementType = 3
	StatementType_UPSERT    StatementType = 4
	StatementType_MERGE     StatementType = 5
	StatementType_OTHER_DML StatementType = 6
	StatementType_CREATE    StatementType = 7
	StatementType_DROP      StatementType = 8
	StatementType_ALTER     StatementType = 9
	StatementType_OTHER_DDL StatementType = 10
	StatementType_CALL      StatementType = 11
)

var StatementType_name = map[int32]string{
	0:  "SELECT",
	1:  "INSERT",
	2:  "UPDATE",
	3:  "DELETE",
	4:  "UPSERT",
	5:  "MERGE",
	6:  "OTHER_DML",
	7:  "CREATE",
	8:  "DROP",
	9:  "ALTER",
	10: "OTHER_DDL",
	11: "CALL",
}
var StatementType_value = map[string]int32{
	"SELECT":    0,
	"INSERT":    1,
	"UPDATE":    2,
	"DELETE":    3,
	"UPSERT":    4,
	"MERGE":     5,
	"OTHER_DML": 6,
	"CREATE":    7,
	"DROP":      8,
	"ALTER":     9,
	"OTHER_DDL": 10,
	"CALL":      11,
}

func (x StatementType) String() string {
	return proto.EnumName(StatementType_name, int32(x))
}
func (StatementType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Rep int32

const (
	Rep_PRIMITIVE_BOOLEAN  Rep = 0
	Rep_PRIMITIVE_BYTE     Rep = 1
	Rep_PRIMITIVE_CHAR     Rep = 2
	Rep_PRIMITIVE_SHORT    Rep = 3
	Rep_PRIMITIVE_INT      Rep = 4
	Rep_PRIMITIVE_LONG     Rep = 5
	Rep_PRIMITIVE_FLOAT    Rep = 6
	Rep_PRIMITIVE_DOUBLE   Rep = 7
	Rep_BOOLEAN            Rep = 8
	Rep_BYTE               Rep = 9
	Rep_CHARACTER          Rep = 10
	Rep_SHORT              Rep = 11
	Rep_INTEGER            Rep = 12
	Rep_LONG               Rep = 13
	Rep_FLOAT              Rep = 14
	Rep_DOUBLE             Rep = 15
	Rep_BIG_INTEGER        Rep = 25
	Rep_BIG_DECIMAL        Rep = 26
	Rep_JAVA_SQL_TIME      Rep = 16
	Rep_JAVA_SQL_TIMESTAMP Rep = 17
	Rep_JAVA_SQL_DATE      Rep = 18
	Rep_JAVA_UTIL_DATE     Rep = 19
	Rep_BYTE_STRING        Rep = 20
	Rep_STRING             Rep = 21
	Rep_NUMBER             Rep = 22
	Rep_OBJECT             Rep = 23
	Rep_NULL               Rep = 24
	Rep_ARRAY              Rep = 27
	Rep_STRUCT             Rep = 28
	Rep_MULTISET           Rep = 29
)

var Rep_name = map[int32]string{
	0:  "PRIMITIVE_BOOLEAN",
	1:  "PRIMITIVE_BYTE",
	2:  "PRIMITIVE_CHAR",
	3:  "PRIMITIVE_SHORT",
	4:  "PRIMITIVE_INT",
	5:  "PRIMITIVE_LONG",
	6:  "PRIMITIVE_FLOAT",
	7:  "PRIMITIVE_DOUBLE",
	8:  "BOOLEAN",
	9:  "BYTE",
	10: "CHARACTER",
	11: "SHORT",
	12: "INTEGER",
	13: "LONG",
	14: "FLOAT",
	15: "DOUBLE",
	25: "BIG_INTEGER",
	26: "BIG_DECIMAL",
	16: "JAVA_SQL_TIME",
	17: "JAVA_SQL_TIMESTAMP",
	18: "JAVA_SQL_DATE",
	19: "JAVA_UTIL_DATE",
	20: "BYTE_STRING",
	21: "STRING",
	22: "NUMBER",
	23: "OBJECT",
	24: "NULL",
	27: "ARRAY",
	28: "STRUCT",
	29: "MULTISET",
}
var Rep_value = map[string]int32{
	"PRIMITIVE_BOOLEAN":  0,
	"PRIMITIVE_BYTE":     1,
	"PRIMITIVE_CHAR":     2,
	"PRIMITIVE_SHORT":    3,
	"PRIMITIVE_INT":      4,
	"PRIMITIVE_LONG":     5,
	"PRIMITIVE_FLOAT":    6,
	"PRIMITIVE_DOUBLE":   7,
	"BOOLEAN":            8,
	"BYTE":               9,
	"CHARACTER":          10,
	"SHORT":              11,
	"INTEGER":            12,
	"LONG":               13,
	"FLOAT":              14,
	"DOUBLE":             15,
	"BIG_INTEGER":        25,
	"BIG_DECIMAL":        26,
	"JAVA_SQL_TIME":      16,
	"JAVA_SQL_TIMESTAMP": 17,
	"JAVA_SQL_DATE":      18,
	"JAVA_UTIL_DATE":     19,
	"BYTE_STRING":        20,
	"STRING":             21,
	"NUMBER":             22,
	"OBJECT":             23,
	"NULL":               24,
	"ARRAY":              27,
	"STRUCT":             28,
	"MULTISET":           29,
}

func (x Rep) String() string {
	return proto.EnumName(Rep_name, int32(x))
}
func (Rep) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// The severity of some unexpected outcome to an operation.
// Protobuf enum values must be unique across all other enums
type Severity int32

const (
	Severity_UNKNOWN_SEVERITY Severity = 0
	Severity_FATAL_SEVERITY   Severity = 1
	Severity_ERROR_SEVERITY   Severity = 2
	Severity_WARNING_SEVERITY Severity = 3
)

var Severity_name = map[int32]string{
	0: "UNKNOWN_SEVERITY",
	1: "FATAL_SEVERITY",
	2: "ERROR_SEVERITY",
	3: "WARNING_SEVERITY",
}
var Severity_value = map[string]int32{
	"UNKNOWN_SEVERITY": 0,
	"FATAL_SEVERITY":   1,
	"ERROR_SEVERITY":   2,
	"WARNING_SEVERITY": 3,
}

func (x Severity) String() string {
	return proto.EnumName(Severity_name, int32(x))
}
func (Severity) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Enumeration corresponding to DatabaseMetaData operations
type MetaDataOperation int32

const (
	MetaDataOperation_GET_ATTRIBUTES             MetaDataOperation = 0
	MetaDataOperation_GET_BEST_ROW_IDENTIFIER    MetaDataOperation = 1
	MetaDataOperation_GET_CATALOGS               MetaDataOperation = 2
	MetaDataOperation_GET_CLIENT_INFO_PROPERTIES MetaDataOperation = 3
	MetaDataOperation_GET_COLUMN_PRIVILEGES      MetaDataOperation = 4
	MetaDataOperation_GET_COLUMNS                MetaDataOperation = 5
	MetaDataOperation_GET_CROSS_REFERENCE        MetaDataOperation = 6
	MetaDataOperation_GET_EXPORTED_KEYS          MetaDataOperation = 7
	MetaDataOperation_GET_FUNCTION_COLUMNS       MetaDataOperation = 8
	MetaDataOperation_GET_FUNCTIONS              MetaDataOperation = 9
	MetaDataOperation_GET_IMPORTED_KEYS          MetaDataOperation = 10
	MetaDataOperation_GET_INDEX_INFO             MetaDataOperation = 11
	MetaDataOperation_GET_PRIMARY_KEYS           MetaDataOperation = 12
	MetaDataOperation_GET_PROCEDURE_COLUMNS      MetaDataOperation = 13
	MetaDataOperation_GET_PROCEDURES             MetaDataOperation = 14
	MetaDataOperation_GET_PSEUDO_COLUMNS         MetaDataOperation = 15
	MetaDataOperation_GET_SCHEMAS                MetaDataOperation = 16
	MetaDataOperation_GET_SCHEMAS_WITH_ARGS      MetaDataOperation = 17
	MetaDataOperation_GET_SUPER_TABLES           MetaDataOperation = 18
	MetaDataOperation_GET_SUPER_TYPES            MetaDataOperation = 19
	MetaDataOperation_GET_TABLE_PRIVILEGES       MetaDataOperation = 20
	MetaDataOperation_GET_TABLES                 MetaDataOperation = 21
	MetaDataOperation_GET_TABLE_TYPES            MetaDataOperation = 22
	MetaDataOperation_GET_TYPE_INFO              MetaDataOperation = 23
	MetaDataOperation_GET_UDTS                   MetaDataOperation = 24
	MetaDataOperation_GET_VERSION_COLUMNS        MetaDataOperation = 25
)

var MetaDataOperation_name = map[int32]string{
	0:  "GET_ATTRIBUTES",
	1:  "GET_BEST_ROW_IDENTIFIER",
	2:  "GET_CATALOGS",
	3:  "GET_CLIENT_INFO_PROPERTIES",
	4:  "GET_COLUMN_PRIVILEGES",
	5:  "GET_COLUMNS",
	6:  "GET_CROSS_REFERENCE",
	7:  "GET_EXPORTED_KEYS",
	8:  "GET_FUNCTION_COLUMNS",
	9:  "GET_FUNCTIONS",
	10: "GET_IMPORTED_KEYS",
	11: "GET_INDEX_INFO",
	12: "GET_PRIMARY_KEYS",
	13: "GET_PROCEDURE_COLUMNS",
	14: "GET_PROCEDURES",
	15: "GET_PSEUDO_COLUMNS",
	16: "GET_SCHEMAS",
	17: "GET_SCHEMAS_WITH_ARGS",
	18: "GET_SUPER_TABLES",
	19: "GET_SUPER_TYPES",
	20: "GET_TABLE_PRIVILEGES",
	21: "GET_TABLES",
	22: "GET_TABLE_TYPES",
	23: "GET_TYPE_INFO",
	24: "GET_UDTS",
	25: "GET_VERSION_COLUMNS",
}
var MetaDataOperation_value = map[string]int32{
	"GET_ATTRIBUTES":             0,
	"GET_BEST_ROW_IDENTIFIER":    1,
	"GET_CATALOGS":               2,
	"GET_CLIENT_INFO_PROPERTIES": 3,
	"GET_COLUMN_PRIVILEGES":      4,
	"GET_COLUMNS":                5,
	"GET_CROSS_REFERENCE":        6,
	"GET_EXPORTED_KEYS":          7,
	"GET_FUNCTION_COLUMNS":       8,
	"GET_FUNCTIONS":              9,
	"GET_IMPORTED_KEYS":          10,
	"GET_INDEX_INFO":             11,
	"GET_PRIMARY_KEYS":           12,
	"GET_PROCEDURE_COLUMNS":      13,
	"GET_PROCEDURES":             14,
	"GET_PSEUDO_COLUMNS":         15,
	"GET_SCHEMAS":                16,
	"GET_SCHEMAS_WITH_ARGS":      17,
	"GET_SUPER_TABLES":           18,
	"GET_SUPER_TYPES":            19,
	"GET_TABLE_PRIVILEGES":       20,
	"GET_TABLES":                 21,
	"GET_TABLE_TYPES":            22,
	"GET_TYPE_INFO":              23,
	"GET_UDTS":                   24,
	"GET_VERSION_COLUMNS":        25,
}

func (x MetaDataOperation) String() string {
	return proto.EnumName(MetaDataOperation_name, int32(x))
}
func (MetaDataOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type StateType int32

const (
	StateType_SQL      StateType = 0
	StateType_METADATA StateType = 1
)

var StateType_name = map[int32]string{
	0: "SQL",
	1: "METADATA",
}
var StateType_value = map[string]int32{
	"SQL":      0,
	"METADATA": 1,
}

func (x StateType) String() string {
	return proto.EnumName(StateType_name, int32(x))
}
func (StateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type CursorFactory_Style int32

const (
	CursorFactory_OBJECT            CursorFactory_Style = 0
	CursorFactory_RECORD            CursorFactory_Style = 1
	CursorFactory_RECORD_PROJECTION CursorFactory_Style = 2
	CursorFactory_ARRAY             CursorFactory_Style = 3
	CursorFactory_LIST              CursorFactory_Style = 4
	CursorFactory_MAP               CursorFactory_Style = 5
)

var CursorFactory_Style_name = map[int32]string{
	0: "OBJECT",
	1: "RECORD",
	2: "RECORD_PROJECTION",
	3: "ARRAY",
	4: "LIST",
	5: "MAP",
}
var CursorFactory_Style_value = map[string]int32{
	"OBJECT":            0,
	"RECORD":            1,
	"RECORD_PROJECTION": 2,
	"ARRAY":             3,
	"LIST":              4,
	"MAP":               5,
}

func (x CursorFactory_Style) String() string {
	return proto.EnumName(CursorFactory_Style_name, int32(x))
}
func (CursorFactory_Style) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type MetaDataOperationArgument_ArgumentType int32

const (
	MetaDataOperationArgument_STRING          MetaDataOperationArgument_ArgumentType = 0
	MetaDataOperationArgument_BOOL            MetaDataOperationArgument_ArgumentType = 1
	MetaDataOperationArgument_INT             MetaDataOperationArgument_ArgumentType = 2
	MetaDataOperationArgument_REPEATED_STRING MetaDataOperationArgument_ArgumentType = 3
	MetaDataOperationArgument_REPEATED_INT    MetaDataOperationArgument_ArgumentType = 4
	MetaDataOperationArgument_NULL            MetaDataOperationArgument_ArgumentType = 5
)

var MetaDataOperationArgument_ArgumentType_name = map[int32]string{
	0: "STRING",
	1: "BOOL",
	2: "INT",
	3: "REPEATED_STRING",
	4: "REPEATED_INT",
	5: "NULL",
}
var MetaDataOperationArgument_ArgumentType_value = map[string]int32{
	"STRING":          0,
	"BOOL":            1,
	"INT":             2,
	"REPEATED_STRING": 3,
	"REPEATED_INT":    4,
	"NULL":            5,
}

func (x MetaDataOperationArgument_ArgumentType) String() string {
	return proto.EnumName(MetaDataOperationArgument_ArgumentType_name, int32(x))
}
func (MetaDataOperationArgument_ArgumentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13, 0}
}

// Details about a connection
type ConnectionProperties struct {
	IsDirty              bool   `protobuf:"varint,1,opt,name=is_dirty,json=isDirty" json:"is_dirty,omitempty"`
	AutoCommit           bool   `protobuf:"varint,2,opt,name=auto_commit,json=autoCommit" json:"auto_commit,omitempty"`
	HasAutoCommit        bool   `protobuf:"varint,7,opt,name=has_auto_commit,json=hasAutoCommit" json:"has_auto_commit,omitempty"`
	ReadOnly             bool   `protobuf:"varint,3,opt,name=read_only,json=readOnly" json:"read_only,omitempty"`
	HasReadOnly          bool   `protobuf:"varint,8,opt,name=has_read_only,json=hasReadOnly" json:"has_read_only,omitempty"`
	TransactionIsolation uint32 `protobuf:"varint,4,opt,name=transaction_isolation,json=transactionIsolation" json:"transaction_isolation,omitempty"`
	Catalog              string `protobuf:"bytes,5,opt,name=catalog" json:"catalog,omitempty"`
	Schema               string `protobuf:"bytes,6,opt,name=schema" json:"schema,omitempty"`
}

func (m *ConnectionProperties) Reset()                    { *m = ConnectionProperties{} }
func (m *ConnectionProperties) String() string            { return proto.CompactTextString(m) }
func (*ConnectionProperties) ProtoMessage()               {}
func (*ConnectionProperties) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConnectionProperties) GetIsDirty() bool {
	if m != nil {
		return m.IsDirty
	}
	return false
}

func (m *ConnectionProperties) GetAutoCommit() bool {
	if m != nil {
		return m.AutoCommit
	}
	return false
}

func (m *ConnectionProperties) GetHasAutoCommit() bool {
	if m != nil {
		return m.HasAutoCommit
	}
	return false
}

func (m *ConnectionProperties) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

func (m *ConnectionProperties) GetHasReadOnly() bool {
	if m != nil {
		return m.HasReadOnly
	}
	return false
}

func (m *ConnectionProperties) GetTransactionIsolation() uint32 {
	if m != nil {
		return m.TransactionIsolation
	}
	return 0
}

func (m *ConnectionProperties) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

func (m *ConnectionProperties) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

// Statement handle
type StatementHandle struct {
	ConnectionId string     `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	Id           uint32     `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Signature    *Signature `protobuf:"bytes,3,opt,name=signature" json:"signature,omitempty"`
}

func (m *StatementHandle) Reset()                    { *m = StatementHandle{} }
func (m *StatementHandle) String() string            { return proto.CompactTextString(m) }
func (*StatementHandle) ProtoMessage()               {}
func (*StatementHandle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StatementHandle) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *StatementHandle) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StatementHandle) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Results of preparing a statement
type Signature struct {
	Columns       []*ColumnMetaData   `protobuf:"bytes,1,rep,name=columns" json:"columns,omitempty"`
	Sql           string              `protobuf:"bytes,2,opt,name=sql" json:"sql,omitempty"`
	Parameters    []*AvaticaParameter `protobuf:"bytes,3,rep,name=parameters" json:"parameters,omitempty"`
	CursorFactory *CursorFactory      `protobuf:"bytes,4,opt,name=cursor_factory,json=cursorFactory" json:"cursor_factory,omitempty"`
	StatementType StatementType       `protobuf:"varint,5,opt,name=statementType,enum=StatementType" json:"statementType,omitempty"`
}

func (m *Signature) Reset()                    { *m = Signature{} }
func (m *Signature) String() string            { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()               {}
func (*Signature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Signature) GetColumns() []*ColumnMetaData {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Signature) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *Signature) GetParameters() []*AvaticaParameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Signature) GetCursorFactory() *CursorFactory {
	if m != nil {
		return m.CursorFactory
	}
	return nil
}

func (m *Signature) GetStatementType() StatementType {
	if m != nil {
		return m.StatementType
	}
	return StatementType_SELECT
}

type ColumnMetaData struct {
	Ordinal            uint32       `protobuf:"varint,1,opt,name=ordinal" json:"ordinal,omitempty"`
	AutoIncrement      bool         `protobuf:"varint,2,opt,name=auto_increment,json=autoIncrement" json:"auto_increment,omitempty"`
	CaseSensitive      bool         `protobuf:"varint,3,opt,name=case_sensitive,json=caseSensitive" json:"case_sensitive,omitempty"`
	Searchable         bool         `protobuf:"varint,4,opt,name=searchable" json:"searchable,omitempty"`
	Currency           bool         `protobuf:"varint,5,opt,name=currency" json:"currency,omitempty"`
	Nullable           uint32       `protobuf:"varint,6,opt,name=nullable" json:"nullable,omitempty"`
	Signed             bool         `protobuf:"varint,7,opt,name=signed" json:"signed,omitempty"`
	DisplaySize        uint32       `protobuf:"varint,8,opt,name=display_size,json=displaySize" json:"display_size,omitempty"`
	Label              string       `protobuf:"bytes,9,opt,name=label" json:"label,omitempty"`
	ColumnName         string       `protobuf:"bytes,10,opt,name=column_name,json=columnName" json:"column_name,omitempty"`
	SchemaName         string       `protobuf:"bytes,11,opt,name=schema_name,json=schemaName" json:"schema_name,omitempty"`
	Precision          uint32       `protobuf:"varint,12,opt,name=precision" json:"precision,omitempty"`
	Scale              uint32       `protobuf:"varint,13,opt,name=scale" json:"scale,omitempty"`
	TableName          string       `protobuf:"bytes,14,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	CatalogName        string       `protobuf:"bytes,15,opt,name=catalog_name,json=catalogName" json:"catalog_name,omitempty"`
	ReadOnly           bool         `protobuf:"varint,16,opt,name=read_only,json=readOnly" json:"read_only,omitempty"`
	Writable           bool         `protobuf:"varint,17,opt,name=writable" json:"writable,omitempty"`
	DefinitelyWritable bool         `protobuf:"varint,18,opt,name=definitely_writable,json=definitelyWritable" json:"definitely_writable,omitempty"`
	ColumnClassName    string       `protobuf:"bytes,19,opt,name=column_class_name,json=columnClassName" json:"column_class_name,omitempty"`
	Type               *AvaticaType `protobuf:"bytes,20,opt,name=type" json:"type,omitempty"`
}

func (m *ColumnMetaData) Reset()                    { *m = ColumnMetaData{} }
func (m *ColumnMetaData) String() string            { return proto.CompactTextString(m) }
func (*ColumnMetaData) ProtoMessage()               {}
func (*ColumnMetaData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ColumnMetaData) GetOrdinal() uint32 {
	if m != nil {
		return m.Ordinal
	}
	return 0
}

func (m *ColumnMetaData) GetAutoIncrement() bool {
	if m != nil {
		return m.AutoIncrement
	}
	return false
}

func (m *ColumnMetaData) GetCaseSensitive() bool {
	if m != nil {
		return m.CaseSensitive
	}
	return false
}

func (m *ColumnMetaData) GetSearchable() bool {
	if m != nil {
		return m.Searchable
	}
	return false
}

func (m *ColumnMetaData) GetCurrency() bool {
	if m != nil {
		return m.Currency
	}
	return false
}

func (m *ColumnMetaData) GetNullable() uint32 {
	if m != nil {
		return m.Nullable
	}
	return 0
}

func (m *ColumnMetaData) GetSigned() bool {
	if m != nil {
		return m.Signed
	}
	return false
}

func (m *ColumnMetaData) GetDisplaySize() uint32 {
	if m != nil {
		return m.DisplaySize
	}
	return 0
}

func (m *ColumnMetaData) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ColumnMetaData) GetColumnName() string {
	if m != nil {
		return m.ColumnName
	}
	return ""
}

func (m *ColumnMetaData) GetSchemaName() string {
	if m != nil {
		return m.SchemaName
	}
	return ""
}

func (m *ColumnMetaData) GetPrecision() uint32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *ColumnMetaData) GetScale() uint32 {
	if m != nil {
		return m.Scale
	}
	return 0
}

func (m *ColumnMetaData) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *ColumnMetaData) GetCatalogName() string {
	if m != nil {
		return m.CatalogName
	}
	return ""
}

func (m *ColumnMetaData) GetReadOnly() bool {
	if m != nil {
		return m.ReadOnly
	}
	return false
}

func (m *ColumnMetaData) GetWritable() bool {
	if m != nil {
		return m.Writable
	}
	return false
}

func (m *ColumnMetaData) GetDefinitelyWritable() bool {
	if m != nil {
		return m.DefinitelyWritable
	}
	return false
}

func (m *ColumnMetaData) GetColumnClassName() string {
	if m != nil {
		return m.ColumnClassName
	}
	return ""
}

func (m *ColumnMetaData) GetType() *AvaticaType {
	if m != nil {
		return m.Type
	}
	return nil
}

// Base class for a column type
type AvaticaType struct {
	Id        uint32            `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Rep       Rep               `protobuf:"varint,3,opt,name=rep,enum=Rep" json:"rep,omitempty"`
	Columns   []*ColumnMetaData `protobuf:"bytes,4,rep,name=columns" json:"columns,omitempty"`
	Component *AvaticaType      `protobuf:"bytes,5,opt,name=component" json:"component,omitempty"`
}

func (m *AvaticaType) Reset()                    { *m = AvaticaType{} }
func (m *AvaticaType) String() string            { return proto.CompactTextString(m) }
func (*AvaticaType) ProtoMessage()               {}
func (*AvaticaType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AvaticaType) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AvaticaType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AvaticaType) GetRep() Rep {
	if m != nil {
		return m.Rep
	}
	return Rep_PRIMITIVE_BOOLEAN
}

func (m *AvaticaType) GetColumns() []*ColumnMetaData {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *AvaticaType) GetComponent() *AvaticaType {
	if m != nil {
		return m.Component
	}
	return nil
}

// Metadata for a parameter
type AvaticaParameter struct {
	Signed        bool   `protobuf:"varint,1,opt,name=signed" json:"signed,omitempty"`
	Precision     uint32 `protobuf:"varint,2,opt,name=precision" json:"precision,omitempty"`
	Scale         uint32 `protobuf:"varint,3,opt,name=scale" json:"scale,omitempty"`
	ParameterType uint32 `protobuf:"varint,4,opt,name=parameter_type,json=parameterType" json:"parameter_type,omitempty"`
	TypeName      string `protobuf:"bytes,5,opt,name=type_name,json=typeName" json:"type_name,omitempty"`
	ClassName     string `protobuf:"bytes,6,opt,name=class_name,json=className" json:"class_name,omitempty"`
	Name          string `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
}

func (m *AvaticaParameter) Reset()                    { *m = AvaticaParameter{} }
func (m *AvaticaParameter) String() string            { return proto.CompactTextString(m) }
func (*AvaticaParameter) ProtoMessage()               {}
func (*AvaticaParameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AvaticaParameter) GetSigned() bool {
	if m != nil {
		return m.Signed
	}
	return false
}

func (m *AvaticaParameter) GetPrecision() uint32 {
	if m != nil {
		return m.Precision
	}
	return 0
}

func (m *AvaticaParameter) GetScale() uint32 {
	if m != nil {
		return m.Scale
	}
	return 0
}

func (m *AvaticaParameter) GetParameterType() uint32 {
	if m != nil {
		return m.ParameterType
	}
	return 0
}

func (m *AvaticaParameter) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *AvaticaParameter) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *AvaticaParameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Information necessary to convert an Iterable into a Calcite Cursor
type CursorFactory struct {
	Style      CursorFactory_Style `protobuf:"varint,1,opt,name=style,enum=CursorFactory_Style" json:"style,omitempty"`
	ClassName  string              `protobuf:"bytes,2,opt,name=class_name,json=className" json:"class_name,omitempty"`
	FieldNames []string            `protobuf:"bytes,3,rep,name=field_names,json=fieldNames" json:"field_names,omitempty"`
}

func (m *CursorFactory) Reset()                    { *m = CursorFactory{} }
func (m *CursorFactory) String() string            { return proto.CompactTextString(m) }
func (*CursorFactory) ProtoMessage()               {}
func (*CursorFactory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CursorFactory) GetStyle() CursorFactory_Style {
	if m != nil {
		return m.Style
	}
	return CursorFactory_OBJECT
}

func (m *CursorFactory) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *CursorFactory) GetFieldNames() []string {
	if m != nil {
		return m.FieldNames
	}
	return nil
}

// A collection of rows
type Frame struct {
	Offset uint64 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Done   bool   `protobuf:"varint,2,opt,name=done" json:"done,omitempty"`
	Rows   []*Row `protobuf:"bytes,3,rep,name=rows" json:"rows,omitempty"`
}

func (m *Frame) Reset()                    { *m = Frame{} }
func (m *Frame) String() string            { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()               {}
func (*Frame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Frame) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Frame) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Frame) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

// A row is a collection of values
type Row struct {
	Value []*ColumnValue `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Row) GetValue() []*ColumnValue {
	if m != nil {
		return m.Value
	}
	return nil
}

// Database property, list of functions the database provides for a certain operation
type DatabaseProperty struct {
	Name      string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Functions []string `protobuf:"bytes,2,rep,name=functions" json:"functions,omitempty"`
}

func (m *DatabaseProperty) Reset()                    { *m = DatabaseProperty{} }
func (m *DatabaseProperty) String() string            { return proto.CompactTextString(m) }
func (*DatabaseProperty) ProtoMessage()               {}
func (*DatabaseProperty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DatabaseProperty) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DatabaseProperty) GetFunctions() []string {
	if m != nil {
		return m.Functions
	}
	return nil
}

// Message which encapsulates another message to support a single RPC endpoint
type WireMessage struct {
	Name           string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	WrappedMessage []byte `protobuf:"bytes,2,opt,name=wrapped_message,json=wrappedMessage,proto3" json:"wrapped_message,omitempty"`
}

func (m *WireMessage) Reset()                    { *m = WireMessage{} }
func (m *WireMessage) String() string            { return proto.CompactTextString(m) }
func (*WireMessage) ProtoMessage()               {}
func (*WireMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *WireMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WireMessage) GetWrappedMessage() []byte {
	if m != nil {
		return m.WrappedMessage
	}
	return nil
}

// A value might be a TypedValue or an Array of TypedValue's
type ColumnValue struct {
	Value         []*TypedValue `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	ArrayValue    []*TypedValue `protobuf:"bytes,2,rep,name=array_value,json=arrayValue" json:"array_value,omitempty"`
	HasArrayValue bool          `protobuf:"varint,3,opt,name=has_array_value,json=hasArrayValue" json:"has_array_value,omitempty"`
	ScalarValue   *TypedValue   `protobuf:"bytes,4,opt,name=scalar_value,json=scalarValue" json:"scalar_value,omitempty"`
}

func (m *ColumnValue) Reset()                    { *m = ColumnValue{} }
func (m *ColumnValue) String() string            { return proto.CompactTextString(m) }
func (*ColumnValue) ProtoMessage()               {}
func (*ColumnValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ColumnValue) GetValue() []*TypedValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ColumnValue) GetArrayValue() []*TypedValue {
	if m != nil {
		return m.ArrayValue
	}
	return nil
}

func (m *ColumnValue) GetHasArrayValue() bool {
	if m != nil {
		return m.HasArrayValue
	}
	return false
}

func (m *ColumnValue) GetScalarValue() *TypedValue {
	if m != nil {
		return m.ScalarValue
	}
	return nil
}

// Generic wrapper to support any SQL type. Struct-like to work around no polymorphism construct.
type TypedValue struct {
	Type        Rep    `protobuf:"varint,1,opt,name=type,enum=Rep" json:"type,omitempty"`
	BoolValue   bool   `protobuf:"varint,2,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	NumberValue int64  `protobuf:"zigzag64,4,opt,name=number_value,json=numberValue" json:"number_value,omitempty"`
	// includes numeric types and date/time types.
	BytesValue  []byte  `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	DoubleValue float64 `protobuf:"fixed64,6,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	Null        bool    `protobuf:"varint,7,opt,name=null" json:"null,omitempty"`
}

func (m *TypedValue) Reset()                    { *m = TypedValue{} }
func (m *TypedValue) String() string            { return proto.CompactTextString(m) }
func (*TypedValue) ProtoMessage()               {}
func (*TypedValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *TypedValue) GetType() Rep {
	if m != nil {
		return m.Type
	}
	return Rep_PRIMITIVE_BOOLEAN
}

func (m *TypedValue) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *TypedValue) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *TypedValue) GetNumberValue() int64 {
	if m != nil {
		return m.NumberValue
	}
	return 0
}

func (m *TypedValue) GetBytesValue() []byte {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *TypedValue) GetDoubleValue() float64 {
	if m != nil {
		return m.DoubleValue
	}
	return 0
}

func (m *TypedValue) GetNull() bool {
	if m != nil {
		return m.Null
	}
	return false
}

// Represents the breadth of arguments to DatabaseMetaData functions
type MetaDataOperationArgument struct {
	StringValue       string                                 `protobuf:"bytes,1,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	BoolValue         bool                                   `protobuf:"varint,2,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
	IntValue          int32                                  `protobuf:"zigzag32,3,opt,name=int_value,json=intValue" json:"int_value,omitempty"`
	StringArrayValues []string                               `protobuf:"bytes,4,rep,name=string_array_values,json=stringArrayValues" json:"string_array_values,omitempty"`
	IntArrayValues    []int32                                `protobuf:"zigzag32,5,rep,packed,name=int_array_values,json=intArrayValues" json:"int_array_values,omitempty"`
	Type              MetaDataOperationArgument_ArgumentType `protobuf:"varint,6,opt,name=type,enum=MetaDataOperationArgument_ArgumentType" json:"type,omitempty"`
}

func (m *MetaDataOperationArgument) Reset()                    { *m = MetaDataOperationArgument{} }
func (m *MetaDataOperationArgument) String() string            { return proto.CompactTextString(m) }
func (*MetaDataOperationArgument) ProtoMessage()               {}
func (*MetaDataOperationArgument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MetaDataOperationArgument) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *MetaDataOperationArgument) GetBoolValue() bool {
	if m != nil {
		return m.BoolValue
	}
	return false
}

func (m *MetaDataOperationArgument) GetIntValue() int32 {
	if m != nil {
		return m.IntValue
	}
	return 0
}

func (m *MetaDataOperationArgument) GetStringArrayValues() []string {
	if m != nil {
		return m.StringArrayValues
	}
	return nil
}

func (m *MetaDataOperationArgument) GetIntArrayValues() []int32 {
	if m != nil {
		return m.IntArrayValues
	}
	return nil
}

func (m *MetaDataOperationArgument) GetType() MetaDataOperationArgument_ArgumentType {
	if m != nil {
		return m.Type
	}
	return MetaDataOperationArgument_STRING
}

type QueryState struct {
	Type    StateType                    `protobuf:"varint,1,opt,name=type,enum=StateType" json:"type,omitempty"`
	Sql     string                       `protobuf:"bytes,2,opt,name=sql" json:"sql,omitempty"`
	Op      MetaDataOperation            `protobuf:"varint,3,opt,name=op,enum=MetaDataOperation" json:"op,omitempty"`
	Args    []*MetaDataOperationArgument `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	HasArgs bool                         `protobuf:"varint,5,opt,name=has_args,json=hasArgs" json:"has_args,omitempty"`
	HasSql  bool                         `protobuf:"varint,6,opt,name=has_sql,json=hasSql" json:"has_sql,omitempty"`
	HasOp   bool                         `protobuf:"varint,7,opt,name=has_op,json=hasOp" json:"has_op,omitempty"`
}

func (m *QueryState) Reset()                    { *m = QueryState{} }
func (m *QueryState) String() string            { return proto.CompactTextString(m) }
func (*QueryState) ProtoMessage()               {}
func (*QueryState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *QueryState) GetType() StateType {
	if m != nil {
		return m.Type
	}
	return StateType_SQL
}

func (m *QueryState) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *QueryState) GetOp() MetaDataOperation {
	if m != nil {
		return m.Op
	}
	return MetaDataOperation_GET_ATTRIBUTES
}

func (m *QueryState) GetArgs() []*MetaDataOperationArgument {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *QueryState) GetHasArgs() bool {
	if m != nil {
		return m.HasArgs
	}
	return false
}

func (m *QueryState) GetHasSql() bool {
	if m != nil {
		return m.HasSql
	}
	return false
}

func (m *QueryState) GetHasOp() bool {
	if m != nil {
		return m.HasOp
	}
	return false
}

func init() {
	proto.RegisterType((*ConnectionProperties)(nil), "ConnectionProperties")
	proto.RegisterType((*StatementHandle)(nil), "StatementHandle")
	proto.RegisterType((*Signature)(nil), "Signature")
	proto.RegisterType((*ColumnMetaData)(nil), "ColumnMetaData")
	proto.RegisterType((*AvaticaType)(nil), "AvaticaType")
	proto.RegisterType((*AvaticaParameter)(nil), "AvaticaParameter")
	proto.RegisterType((*CursorFactory)(nil), "CursorFactory")
	proto.RegisterType((*Frame)(nil), "Frame")
	proto.RegisterType((*Row)(nil), "Row")
	proto.RegisterType((*DatabaseProperty)(nil), "DatabaseProperty")
	proto.RegisterType((*WireMessage)(nil), "WireMessage")
	proto.RegisterType((*ColumnValue)(nil), "ColumnValue")
	proto.RegisterType((*TypedValue)(nil), "TypedValue")
	proto.RegisterType((*MetaDataOperationArgument)(nil), "MetaDataOperationArgument")
	proto.RegisterType((*QueryState)(nil), "QueryState")
	proto.RegisterEnum("StatementType", StatementType_name, StatementType_value)
	proto.RegisterEnum("Rep", Rep_name, Rep_value)
	proto.RegisterEnum("Severity", Severity_name, Severity_value)
	proto.RegisterEnum("MetaDataOperation", MetaDataOperation_name, MetaDataOperation_value)
	proto.RegisterEnum("StateType", StateType_name, StateType_value)
	proto.RegisterEnum("CursorFactory_Style", CursorFactory_Style_name, CursorFactory_Style_value)
	proto.RegisterEnum("MetaDataOperationArgument_ArgumentType", MetaDataOperationArgument_ArgumentType_name, MetaDataOperationArgument_ArgumentType_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x58, 0xcb, 0x72, 0xe3, 0xc6,
	0x15, 0x1d, 0xf0, 0x21, 0x91, 0x17, 0x24, 0xd5, 0x6a, 0x49, 0x33, 0x9c, 0x19, 0x3f, 0x64, 0xa6,
	0x1c, 0xcb, 0xaa, 0x14, 0x53, 0x91, 0x93, 0x55, 0x56, 0x10, 0xd9, 0x92, 0x60, 0x93, 0x04, 0xdd,
	0x00, 0x25, 0x6b, 0x63, 0x14, 0x04, 0xb6, 0x24, 0x54, 0x41, 0x00, 0x0d, 0x80, 0x33, 0x45, 0xff,
	0x45, 0xbe, 0x20, 0xa9, 0x7c, 0x44, 0xfe, 0x23, 0x8b, 0x54, 0x56, 0xd9, 0x24, 0x9b, 0x6c, 0xf3,
	0x07, 0xa9, 0xdb, 0x0d, 0x90, 0xe0, 0x3c, 0xca, 0x2b, 0x75, 0x9f, 0x7b, 0xfa, 0xe2, 0xbe, 0xbb,
	0x45, 0x68, 0xf9, 0xf1, 0xd3, 0x53, 0x1c, 0xf5, 0x17, 0x49, 0x9c, 0xc5, 0xbd, 0xbf, 0x56, 0xe0,
	0x70, 0x10, 0x47, 0x91, 0xf0, 0xb3, 0x20, 0x8e, 0xa6, 0x49, 0xbc, 0x10, 0x49, 0x16, 0x88, 0x94,
	0xbe, 0x84, 0x46, 0x90, 0xba, 0xf3, 0x20, 0xc9, 0x56, 0x5d, 0xed, 0x58, 0x3b, 0x69, 0xf0, 0xdd,
	0x20, 0x1d, 0xe2, 0x96, 0x7e, 0x0e, 0xba, 0xb7, 0xcc, 0x62, 0x17, 0x15, 0x05, 0x59, 0xb7, 0x22,
	0xa5, 0x80, 0xd0, 0x40, 0x22, 0xf4, 0xd7, 0xb0, 0xf7, 0xe8, 0xa5, 0x6e, 0x99, 0xb4, 0x2b, 0x49,
	0xed, 0x47, 0x2f, 0x35, 0x36, 0xbc, 0xd7, 0xd0, 0x4c, 0x84, 0x37, 0x77, 0xe3, 0x28, 0x5c, 0x75,
	0xab, 0x92, 0xd1, 0x40, 0xc0, 0x8a, 0xc2, 0x15, 0xed, 0x01, 0xb2, 0xdd, 0x0d, 0xa1, 0x21, 0x09,
	0xfa, 0xa3, 0x97, 0xf2, 0x82, 0xf3, 0x0d, 0x1c, 0x65, 0x89, 0x17, 0xa5, 0x9e, 0xb4, 0xde, 0x0d,
	0xd2, 0x38, 0xf4, 0x70, 0xd5, 0xad, 0x1d, 0x6b, 0x27, 0x6d, 0x7e, 0x58, 0x12, 0x9a, 0x85, 0x8c,
	0x76, 0x61, 0xd7, 0xf7, 0x32, 0x2f, 0x8c, 0x1f, 0xba, 0xf5, 0x63, 0xed, 0xa4, 0xc9, 0x8b, 0x2d,
	0x7d, 0x0e, 0x3b, 0xa9, 0xff, 0x28, 0x9e, 0xbc, 0xee, 0x8e, 0x14, 0xe4, 0xbb, 0xde, 0x02, 0xf6,
	0xec, 0xcc, 0xcb, 0xc4, 0x93, 0x88, 0xb2, 0x2b, 0x2f, 0x9a, 0x87, 0x82, 0xfe, 0x0a, 0xda, 0xfe,
	0x3a, 0x6c, 0x6e, 0x30, 0x97, 0x31, 0x6a, 0xf2, 0xd6, 0x06, 0x34, 0xe7, 0xb4, 0x03, 0x95, 0x60,
	0x2e, 0xe3, 0xd3, 0xe6, 0x95, 0x60, 0x4e, 0x4f, 0xa0, 0x99, 0x06, 0x0f, 0x91, 0x97, 0x2d, 0x13,
	0x21, 0xfd, 0xd5, 0xcf, 0xa0, 0x6f, 0x17, 0x08, 0xdf, 0x08, 0x7b, 0xff, 0xd5, 0xa0, 0xb9, 0x16,
	0xd0, 0xaf, 0x61, 0xd7, 0x8f, 0xc3, 0xe5, 0x53, 0x94, 0x76, 0xb5, 0xe3, 0xea, 0x89, 0x7e, 0xb6,
	0xd7, 0x1f, 0xc8, 0xfd, 0x58, 0x64, 0xde, 0xd0, 0xcb, 0x3c, 0x5e, 0xc8, 0x29, 0x81, 0x6a, 0xfa,
	0x53, 0x28, 0xbf, 0xd9, 0xe4, 0xb8, 0xa4, 0xbf, 0x03, 0x58, 0x78, 0x89, 0xf7, 0x24, 0x32, 0x91,
	0xa4, 0xdd, 0xaa, 0x3c, 0xbf, 0xdf, 0x37, 0xde, 0x78, 0x59, 0xe0, 0x7b, 0xd3, 0x42, 0xc2, 0x4b,
	0x24, 0xfa, 0x07, 0xe8, 0xf8, 0xcb, 0x24, 0x8d, 0x13, 0xf7, 0xde, 0xf3, 0xb3, 0x38, 0x59, 0xc9,
	0x78, 0xea, 0x67, 0x9d, 0xfe, 0x40, 0xc2, 0x17, 0x0a, 0xe5, 0x6d, 0xbf, 0xbc, 0xa5, 0xbf, 0x87,
	0x76, 0x5a, 0x84, 0xc9, 0x59, 0x2d, 0x84, 0x0c, 0x6f, 0xe7, 0xac, 0xd3, 0xb7, 0xcb, 0x28, 0xdf,
	0x26, 0xf5, 0xfe, 0x54, 0x87, 0xce, 0xb6, 0x37, 0x98, 0xa1, 0x38, 0x99, 0x07, 0x91, 0x17, 0xca,
	0xb0, 0xb6, 0x79, 0xb1, 0xa5, 0x5f, 0x42, 0x47, 0x56, 0x55, 0x10, 0xf9, 0x89, 0x54, 0x91, 0x57,
	0x5f, 0x1b, 0x51, 0xb3, 0x00, 0x91, 0xe6, 0x7b, 0xa9, 0x70, 0x53, 0x11, 0xa5, 0x41, 0x16, 0xbc,
	0x11, 0x79, 0x75, 0xb5, 0x11, 0xb5, 0x0b, 0x90, 0x7e, 0x06, 0x90, 0x0a, 0x2f, 0xf1, 0x1f, 0xbd,
	0xbb, 0x50, 0x48, 0x1f, 0x1b, 0xbc, 0x84, 0xd0, 0x57, 0xd0, 0xf0, 0x97, 0x49, 0x22, 0x22, 0x7f,
	0x25, 0x7d, 0x69, 0xf0, 0xf5, 0x1e, 0x65, 0xd1, 0x32, 0x0c, 0xe5, 0xc9, 0x1d, 0x69, 0xe4, 0x7a,
	0x2f, 0xeb, 0x28, 0x78, 0x88, 0xc4, 0x3c, 0x2f, 0xfb, 0x7c, 0x47, 0xbf, 0x80, 0xd6, 0x3c, 0x48,
	0x17, 0xa1, 0xb7, 0x72, 0xd3, 0xe0, 0x67, 0x21, 0x2b, 0xba, 0xcd, 0xf5, 0x1c, 0xb3, 0x83, 0x9f,
	0x05, 0x3d, 0x84, 0x7a, 0xe8, 0xdd, 0x89, 0xb0, 0xdb, 0x94, 0x19, 0x54, 0x1b, 0xec, 0x38, 0x95,
	0x60, 0x37, 0xf2, 0x9e, 0x44, 0x17, 0xa4, 0x0c, 0x14, 0x34, 0xf1, 0x9e, 0x04, 0x12, 0x54, 0xad,
	0x2a, 0x82, 0xae, 0x08, 0x0a, 0x92, 0x84, 0x4f, 0xa0, 0xb9, 0x48, 0x84, 0x1f, 0xa4, 0xd8, 0x1d,
	0x2d, 0xf9, 0xdd, 0x0d, 0x80, 0x5f, 0x4d, 0x7d, 0x2f, 0x14, 0xdd, 0xb6, 0x94, 0xa8, 0x0d, 0xfd,
	0x14, 0x20, 0x43, 0x7f, 0x94, 0xce, 0x8e, 0xd4, 0xd9, 0x94, 0x88, 0x54, 0xf9, 0x05, 0xb4, 0xf2,
	0xc6, 0x51, 0x84, 0x3d, 0x49, 0xd0, 0x73, 0x4c, 0x52, 0xb6, 0x1a, 0x9c, 0xbc, 0xd3, 0xe0, 0xaf,
	0xa0, 0xf1, 0x36, 0x09, 0xa4, 0xbe, 0xee, 0xbe, 0x92, 0x15, 0x7b, 0xfa, 0x5b, 0x38, 0x98, 0x8b,
	0xfb, 0x20, 0x0a, 0x32, 0x11, 0xae, 0xdc, 0x35, 0x8d, 0x4a, 0x1a, 0xdd, 0x88, 0x6e, 0x8a, 0x03,
	0xa7, 0xb0, 0x9f, 0x47, 0xc8, 0x0f, 0xbd, 0x34, 0x55, 0x16, 0x1d, 0x48, 0x8b, 0xf6, 0x94, 0x60,
	0x80, 0xb8, 0xb4, 0xea, 0x18, 0x6a, 0x19, 0x96, 0xe7, 0xa1, 0x2c, 0xea, 0x56, 0xd1, 0x0b, 0xb2,
	0x38, 0xa5, 0xa4, 0xf7, 0x17, 0x0d, 0xf4, 0x12, 0x9a, 0x37, 0xb2, 0xb6, 0x6e, 0x64, 0x0a, 0x35,
	0xf9, 0x01, 0xd5, 0x66, 0x72, 0x4d, 0x9f, 0x43, 0x35, 0x11, 0x0b, 0x59, 0x68, 0x9d, 0xb3, 0x5a,
	0x9f, 0x8b, 0x05, 0x47, 0xa0, 0xdc, 0xbc, 0xb5, 0x5f, 0x68, 0xde, 0x53, 0x68, 0xfa, 0xf1, 0xd3,
	0x22, 0x8e, 0xb0, 0xb0, 0xeb, 0x1f, 0xb0, 0x6e, 0x23, 0xee, 0xfd, 0x43, 0x03, 0xf2, 0x6e, 0x13,
	0x97, 0x0a, 0x4f, 0xdb, 0x2a, 0xbc, 0xad, 0xec, 0x57, 0x3e, 0x9a, 0xfd, 0x6a, 0x39, 0xfb, 0x5f,
	0x42, 0x67, 0x3d, 0x12, 0x5c, 0x19, 0x2f, 0x35, 0x54, 0xdb, 0x6b, 0x54, 0x86, 0xe6, 0x35, 0x34,
	0x51, 0xa8, 0x02, 0xae, 0xe6, 0x69, 0x03, 0x01, 0x19, 0xe9, 0x4f, 0x01, 0x4a, 0xe9, 0x50, 0x43,
	0xb5, 0xe9, 0xaf, 0x13, 0x51, 0x84, 0x71, 0x77, 0x13, 0xc6, 0xde, 0xdf, 0x35, 0x68, 0x6f, 0x4d,
	0x19, 0x7a, 0x0a, 0xf5, 0x34, 0x5b, 0x85, 0x42, 0xfa, 0xd4, 0x39, 0x3b, 0xdc, 0x1e, 0x42, 0x7d,
	0x1b, 0x65, 0x5c, 0x51, 0xde, 0xf9, 0x60, 0xe5, 0xdd, 0x0f, 0x7e, 0x0e, 0xfa, 0x7d, 0x20, 0xc2,
	0xb9, 0x14, 0xab, 0x61, 0xd8, 0xe4, 0x20, 0x21, 0x94, 0xa7, 0x3d, 0x07, 0xea, 0x52, 0x1f, 0x05,
	0xd8, 0xb1, 0xce, 0xbf, 0x65, 0x03, 0x87, 0x3c, 0xc3, 0x35, 0x67, 0x03, 0x8b, 0x0f, 0x89, 0x46,
	0x8f, 0x60, 0x5f, 0xad, 0xdd, 0x29, 0xb7, 0x50, 0x6e, 0x5a, 0x13, 0x52, 0xa1, 0x4d, 0xa8, 0x1b,
	0x9c, 0x1b, 0xb7, 0xa4, 0x4a, 0x1b, 0x50, 0x1b, 0x99, 0xb6, 0x43, 0x6a, 0x74, 0x17, 0xaa, 0x63,
	0x63, 0x4a, 0xea, 0xbd, 0x31, 0xd4, 0x2f, 0x12, 0x55, 0x23, 0x3b, 0xf1, 0xfd, 0x7d, 0x2a, 0x32,
	0xe9, 0x4b, 0x8d, 0xe7, 0x3b, 0x0c, 0xc4, 0x3c, 0x8e, 0x44, 0x3e, 0xcc, 0xe4, 0x9a, 0x76, 0xa1,
	0x96, 0xc4, 0x6f, 0x8b, 0x89, 0x5d, 0xeb, 0xf3, 0xf8, 0x2d, 0x97, 0x48, 0xef, 0x6b, 0xa8, 0xf2,
	0xf8, 0x2d, 0xed, 0x41, 0xfd, 0x8d, 0x17, 0x2e, 0x45, 0x7e, 0x27, 0xb4, 0xf2, 0xb2, 0xba, 0x46,
	0x8c, 0x2b, 0x51, 0x6f, 0x08, 0x04, 0x4b, 0xec, 0xce, 0x4b, 0x45, 0x7e, 0xb7, 0xaf, 0xd6, 0x51,
	0xd7, 0x4a, 0xc5, 0xfb, 0x09, 0x34, 0xef, 0x97, 0x91, 0xbc, 0xb7, 0xd2, 0x6e, 0x45, 0x86, 0x65,
	0x03, 0xf4, 0xbe, 0x05, 0xfd, 0x26, 0x48, 0xc4, 0x58, 0xa4, 0xa9, 0xf7, 0x20, 0x3e, 0xa8, 0xe0,
	0x2b, 0xd8, 0x7b, 0x9b, 0x78, 0x8b, 0x85, 0x98, 0xbb, 0x4f, 0x8a, 0x26, 0x9d, 0x69, 0xf1, 0x4e,
	0x0e, 0xe7, 0x87, 0x7b, 0x7f, 0xd3, 0x40, 0x2f, 0x19, 0x4a, 0xbf, 0xd8, 0xf6, 0x42, 0xef, 0x63,
	0x55, 0xcd, 0xcb, 0x4e, 0xd0, 0xdf, 0x80, 0xee, 0x25, 0x89, 0xb7, 0x72, 0x15, 0xb1, 0xf2, 0x3e,
	0x11, 0xa4, 0x5c, 0x29, 0x2c, 0x1e, 0x1f, 0xa5, 0x13, 0xd5, 0xcd, 0xe3, 0x63, 0xc3, 0xeb, 0x43,
	0x0b, 0x0b, 0xdd, 0x4b, 0x72, 0x92, 0xba, 0xe2, 0xb6, 0xd4, 0xea, 0x8a, 0x20, 0x37, 0xbd, 0xff,
	0x68, 0x00, 0x1b, 0x19, 0xa6, 0x47, 0x36, 0x85, 0x56, 0xea, 0x77, 0x89, 0x60, 0x0d, 0xde, 0xc5,
	0x71, 0xb8, 0xb6, 0x16, 0xbf, 0xdd, 0x44, 0xa4, 0x70, 0xb8, 0x95, 0x66, 0x49, 0x10, 0x3d, 0x94,
	0x8c, 0x6b, 0x72, 0x5d, 0x61, 0x6b, 0x4a, 0xb4, 0x7c, 0xba, 0x13, 0x65, 0xd3, 0x28, 0xd7, 0x15,
	0xa6, 0x28, 0x9f, 0x83, 0x7e, 0xb7, 0xca, 0x44, 0x9a, 0x33, 0xea, 0x32, 0xd6, 0x20, 0xa1, 0xb5,
	0x8e, 0x79, 0xbc, 0xc4, 0xe9, 0xad, 0x18, 0xd8, 0x7c, 0x1a, 0xd7, 0x15, 0xa6, 0x28, 0x98, 0xc7,
	0x65, 0x18, 0xe6, 0x97, 0x94, 0x5c, 0xf7, 0xfe, 0x57, 0x81, 0x97, 0xc5, 0x60, 0xb2, 0x16, 0x22,
	0x91, 0x4f, 0x26, 0x23, 0x79, 0x58, 0xca, 0x7b, 0xf5, 0x5d, 0xdb, 0xb5, 0xf7, 0x6d, 0xff, 0x05,
	0xef, 0x5f, 0x43, 0x33, 0x88, 0xb2, 0x92, 0xeb, 0xfb, 0xbc, 0x11, 0x44, 0x59, 0x91, 0x92, 0x83,
	0x5c, 0x7d, 0x29, 0x7b, 0x6a, 0x6c, 0x36, 0xf9, 0xbe, 0x12, 0x6d, 0x32, 0x98, 0xd2, 0x13, 0x20,
	0xa8, 0x6c, 0x8b, 0x5c, 0x3f, 0xae, 0x9e, 0xec, 0xf3, 0x4e, 0x10, 0x65, 0x65, 0xe6, 0x1f, 0xf3,
	0x6c, 0xed, 0xc8, 0x6c, 0x7d, 0xd5, 0xff, 0xa8, 0x8b, 0xfd, 0x62, 0x51, 0xba, 0x0d, 0x7e, 0x84,
	0x56, 0x19, 0xc5, 0x79, 0x60, 0x3b, 0xdc, 0x9c, 0x5c, 0x92, 0x67, 0xd8, 0xed, 0xe7, 0x96, 0x35,
	0x22, 0x1a, 0x76, 0xbb, 0x39, 0x71, 0x48, 0x85, 0x1e, 0xc0, 0x1e, 0x67, 0x53, 0x66, 0x38, 0x6c,
	0xe8, 0xe6, 0xbc, 0x2a, 0x25, 0xd0, 0x5a, 0x83, 0x48, 0xab, 0xe1, 0xc9, 0xc9, 0x6c, 0x34, 0x22,
	0xf5, 0xde, 0xbf, 0x34, 0x80, 0xef, 0x97, 0x22, 0x59, 0xc9, 0x77, 0x12, 0xfd, 0x6c, 0xab, 0xb2,
	0x40, 0xbd, 0x9e, 0x36, 0xe6, 0x7c, 0xe0, 0x89, 0xd7, 0x83, 0x4a, 0x5c, 0xdc, 0x3c, 0xf4, 0x7d,
	0xdf, 0x78, 0x25, 0x5e, 0xd0, 0x3e, 0xd4, 0xbc, 0xe4, 0xa1, 0xb8, 0x83, 0x5e, 0x7d, 0x3c, 0x02,
	0x5c, 0xf2, 0xf0, 0xfd, 0xaf, 0xda, 0xe8, 0x21, 0xcd, 0xdf, 0x3e, 0xbb, 0xb2, 0x7f, 0x1e, 0x52,
	0xfa, 0x02, 0x70, 0xe9, 0xa2, 0x11, 0x3b, 0xea, 0x9a, 0x79, 0xf4, 0x52, 0xfb, 0xa7, 0x90, 0x1e,
	0x01, 0xae, 0xdc, 0x78, 0x91, 0x97, 0x54, 0xfd, 0xd1, 0x4b, 0xad, 0xc5, 0xe9, 0x9f, 0x35, 0x68,
	0x6f, 0x3d, 0x01, 0x65, 0x04, 0xd9, 0x68, 0x3d, 0x5d, 0xcd, 0x89, 0xcd, 0xb8, 0x43, 0x34, 0x5c,
	0xcf, 0xa6, 0x43, 0xc3, 0x61, 0xa4, 0x82, 0xeb, 0x21, 0x1b, 0x31, 0x87, 0x91, 0xaa, 0xc2, 0x25,
	0xa7, 0x86, 0xa3, 0x76, 0xcc, 0xf8, 0x25, 0x23, 0x75, 0xda, 0x86, 0xa6, 0xe5, 0x5c, 0x31, 0xee,
	0x0e, 0xc7, 0x23, 0xb2, 0x83, 0xac, 0x01, 0xc7, 0x10, 0x93, 0x5d, 0x8c, 0xee, 0x90, 0x5b, 0x53,
	0xd2, 0x90, 0xa3, 0x79, 0xe4, 0x30, 0x4e, 0x9a, 0x25, 0xfe, 0x70, 0x44, 0x00, 0x39, 0x03, 0x63,
	0x34, 0x22, 0xfa, 0xe9, 0xbf, 0xab, 0x50, 0xe5, 0x62, 0x81, 0xd3, 0x7d, 0xca, 0xcd, 0xb1, 0xe9,
	0x98, 0xd7, 0xcc, 0xc5, 0xbc, 0x32, 0x63, 0x42, 0x9e, 0x51, 0x0a, 0x9d, 0x12, 0x7c, 0xeb, 0x30,
	0xa2, 0x6d, 0x63, 0x83, 0x2b, 0x83, 0xab, 0xcc, 0x6f, 0x30, 0xfb, 0xca, 0xe2, 0x0e, 0xa9, 0xd2,
	0x7d, 0x68, 0x6f, 0x40, 0x95, 0xfa, 0xad, 0xb3, 0x23, 0x6b, 0x72, 0x49, 0xea, 0xdb, 0x67, 0x2f,
	0x46, 0x96, 0xe1, 0x90, 0x1d, 0x7a, 0x08, 0x64, 0x03, 0x0e, 0xad, 0xd9, 0xf9, 0x08, 0x7d, 0xd3,
	0x61, 0xb7, 0xb0, 0xad, 0x21, 0x0b, 0x10, 0x2d, 0x92, 0xde, 0xa1, 0x1d, 0xc6, 0x00, 0x9d, 0x05,
	0xf4, 0x5b, 0x99, 0xa0, 0xe3, 0x01, 0x73, 0xe2, 0xb0, 0x4b, 0xc6, 0x49, 0x4b, 0xde, 0x4f, 0xf8,
	0xc9, 0x36, 0x32, 0xd4, 0x87, 0x3a, 0x32, 0xd8, 0x4a, 0xfd, 0x1e, 0xdd, 0x03, 0xfd, 0xdc, 0xbc,
	0x74, 0x8b, 0x13, 0x2f, 0x0b, 0x60, 0xc8, 0x06, 0xe6, 0xd8, 0x18, 0x91, 0x57, 0xe8, 0xd2, 0xb7,
	0xc6, 0xb5, 0xe1, 0xda, 0xdf, 0x8f, 0x5c, 0xc7, 0x1c, 0x33, 0x42, 0xe8, 0x73, 0xa0, 0x5b, 0x90,
	0xed, 0x18, 0xe3, 0x29, 0xd9, 0xdf, 0xa2, 0xca, 0xc4, 0x52, 0xf4, 0x5e, 0x42, 0x33, 0xc7, 0xcc,
	0xb1, 0x03, 0xf9, 0x89, 0x5b, 0x87, 0x15, 0xfd, 0x72, 0x58, 0xea, 0xb1, 0x23, 0x5c, 0x4f, 0x66,
	0xe3, 0x73, 0xc6, 0xc9, 0xf3, 0xd2, 0xbd, 0xfc, 0x62, 0xdd, 0x41, 0xdd, 0xcd, 0xf5, 0xfb, 0x3a,
	0x3f, 0x38, 0x1b, 0x38, 0xe4, 0x13, 0xda, 0x82, 0xc6, 0x78, 0x36, 0x72, 0x4c, 0x9b, 0x39, 0xe4,
	0xd3, 0xd3, 0x1f, 0xa1, 0x61, 0x8b, 0x37, 0x22, 0x09, 0xb2, 0x15, 0x06, 0x76, 0x36, 0xf9, 0x6e,
	0x62, 0xdd, 0x4c, 0x5c, 0x9b, 0x5d, 0x33, 0x6e, 0x3a, 0xb7, 0x2a, 0xcf, 0x17, 0x86, 0x63, 0x8c,
	0x36, 0x98, 0xcc, 0x33, 0xe3, 0xdc, 0xe2, 0x1b, 0xac, 0x82, 0xa7, 0x6f, 0x0c, 0x3e, 0x31, 0x27,
	0x97, 0x1b, 0xb4, 0x7a, 0xfa, 0xcf, 0x1a, 0xec, 0xbf, 0xd7, 0x55, 0x78, 0xfe, 0x92, 0x39, 0xae,
	0xe1, 0x38, 0xdc, 0x3c, 0x9f, 0x39, 0xcc, 0x26, 0xcf, 0xe8, 0x6b, 0x78, 0x81, 0xd8, 0x39, 0xb3,
	0x1d, 0x97, 0x5b, 0x37, 0xae, 0x39, 0x64, 0x13, 0xc7, 0xbc, 0x30, 0x19, 0x27, 0x1a, 0x4e, 0x0a,
	0x14, 0x0e, 0xd0, 0x10, 0xeb, 0xd2, 0x26, 0x15, 0xfa, 0x19, 0xbc, 0x92, 0xc8, 0xc8, 0x64, 0x13,
	0xc7, 0x35, 0x27, 0x17, 0x16, 0x3e, 0x3e, 0xa6, 0x8c, 0x3b, 0x26, 0xb3, 0x49, 0x95, 0xbe, 0x84,
	0x23, 0x29, 0xb7, 0x46, 0xb3, 0xf1, 0xc4, 0x9d, 0x72, 0xf3, 0xda, 0x1c, 0xb1, 0x4b, 0x66, 0x93,
	0x1a, 0xc6, 0x75, 0x23, 0xb2, 0x49, 0x9d, 0xbe, 0x80, 0x03, 0x09, 0x70, 0xcb, 0xb6, 0x5d, 0xce,
	0x2e, 0x18, 0x67, 0x93, 0x01, 0x23, 0x3b, 0x58, 0xfa, 0x28, 0x60, 0x3f, 0x4c, 0x2d, 0x8e, 0x43,
	0xea, 0x3b, 0x76, 0x6b, 0x93, 0x5d, 0xda, 0x85, 0x43, 0x84, 0x2f, 0x66, 0x13, 0xf9, 0xd4, 0x59,
	0x6b, 0x6a, 0x60, 0x66, 0xcb, 0x12, 0x9b, 0x34, 0x0b, 0x1d, 0xe6, 0xb8, 0xac, 0x03, 0x8a, 0x10,
	0x98, 0x93, 0x21, 0xfb, 0x41, 0x9a, 0x4f, 0x74, 0x0c, 0x21, 0x62, 0x58, 0xdd, 0x06, 0xbf, 0x55,
	0xcc, 0x56, 0xe1, 0xc9, 0x94, 0x5b, 0x03, 0x36, 0x9c, 0x71, 0xb6, 0xfe, 0x5c, 0xbb, 0x50, 0xb2,
	0x16, 0xd9, 0xa4, 0x83, 0x45, 0x27, 0x31, 0x9b, 0xcd, 0x86, 0xd6, 0x9a, 0xbb, 0x57, 0x78, 0x6d,
	0x0f, 0xae, 0xd8, 0xd8, 0xb0, 0x09, 0x29, 0xf4, 0xe6, 0x80, 0x7b, 0x63, 0x3a, 0x57, 0xae, 0xc1,
	0x2f, 0x6d, 0xb2, 0x5f, 0x18, 0x62, 0xcf, 0xa6, 0x8c, 0xbb, 0x8e, 0x71, 0x3e, 0x62, 0x36, 0xa1,
	0xd8, 0x8d, 0x25, 0xf4, 0x76, 0xca, 0x6c, 0x72, 0x50, 0xc4, 0x42, 0x92, 0xca, 0x61, 0x3e, 0xa4,
	0x1d, 0x80, 0xb5, 0xc4, 0x26, 0x47, 0xc5, 0x71, 0xc5, 0x54, 0xc7, 0x9f, 0x17, 0x01, 0xc3, 0xad,
	0x8a, 0xc2, 0x0b, 0x2c, 0x50, 0x84, 0x66, 0x43, 0xc7, 0x26, 0xdd, 0x22, 0x37, 0xd7, 0x8c, 0xdb,
	0xe5, 0x50, 0xbf, 0x3c, 0xed, 0x41, 0x73, 0x7d, 0x09, 0xe0, 0x3d, 0x63, 0x7f, 0x3f, 0x22, 0xcf,
	0x64, 0x75, 0x33, 0xc7, 0x18, 0x1a, 0x8e, 0x41, 0xb4, 0xf3, 0x1e, 0x1c, 0xc7, 0xc9, 0x43, 0xdf,
	0x5b, 0x78, 0xfe, 0xa3, 0xe8, 0xfb, 0x5e, 0xe8, 0x07, 0x99, 0xe8, 0x7b, 0xea, 0x3f, 0x04, 0xf5,
	0x63, 0xcf, 0xdd, 0x8e, 0xfc, 0xf3, 0xcd, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x30, 0x15, 0x1a,
	0xdd, 0x03, 0x12, 0x00, 0x00,
}
