// Code generated by protoc-gen-go.
// source: requests.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Request for Meta#getCatalogs()
type CatalogsRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *CatalogsRequest) Reset()                    { *m = CatalogsRequest{} }
func (m *CatalogsRequest) String() string            { return proto.CompactTextString(m) }
func (*CatalogsRequest) ProtoMessage()               {}
func (*CatalogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CatalogsRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request for Meta#getDatabaseProperties()
type DatabasePropertyRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *DatabasePropertyRequest) Reset()                    { *m = DatabasePropertyRequest{} }
func (m *DatabasePropertyRequest) String() string            { return proto.CompactTextString(m) }
func (*DatabasePropertyRequest) ProtoMessage()               {}
func (*DatabasePropertyRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *DatabasePropertyRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request for Meta#getSchemas(String, org.apache.calcite.avatica.Meta.Pat)}
type SchemasRequest struct {
	Catalog       string `protobuf:"bytes,1,opt,name=catalog" json:"catalog,omitempty"`
	SchemaPattern string `protobuf:"bytes,2,opt,name=schema_pattern,json=schemaPattern" json:"schema_pattern,omitempty"`
	ConnectionId  string `protobuf:"bytes,3,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *SchemasRequest) Reset()                    { *m = SchemasRequest{} }
func (m *SchemasRequest) String() string            { return proto.CompactTextString(m) }
func (*SchemasRequest) ProtoMessage()               {}
func (*SchemasRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *SchemasRequest) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

func (m *SchemasRequest) GetSchemaPattern() string {
	if m != nil {
		return m.SchemaPattern
	}
	return ""
}

func (m *SchemasRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request for Request for Meta#getTables(String, org.apache.calcite.avatica.Meta.Pat,
//   org.apache.calcite.avatica.Meta.Pat, java.util.List)
type TablesRequest struct {
	Catalog          string   `protobuf:"bytes,1,opt,name=catalog" json:"catalog,omitempty"`
	SchemaPattern    string   `protobuf:"bytes,2,opt,name=schema_pattern,json=schemaPattern" json:"schema_pattern,omitempty"`
	TableNamePattern string   `protobuf:"bytes,3,opt,name=table_name_pattern,json=tableNamePattern" json:"table_name_pattern,omitempty"`
	TypeList         []string `protobuf:"bytes,4,rep,name=type_list,json=typeList" json:"type_list,omitempty"`
	HasTypeList      bool     `protobuf:"varint,6,opt,name=has_type_list,json=hasTypeList" json:"has_type_list,omitempty"`
	ConnectionId     string   `protobuf:"bytes,7,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *TablesRequest) Reset()                    { *m = TablesRequest{} }
func (m *TablesRequest) String() string            { return proto.CompactTextString(m) }
func (*TablesRequest) ProtoMessage()               {}
func (*TablesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *TablesRequest) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

func (m *TablesRequest) GetSchemaPattern() string {
	if m != nil {
		return m.SchemaPattern
	}
	return ""
}

func (m *TablesRequest) GetTableNamePattern() string {
	if m != nil {
		return m.TableNamePattern
	}
	return ""
}

func (m *TablesRequest) GetTypeList() []string {
	if m != nil {
		return m.TypeList
	}
	return nil
}

func (m *TablesRequest) GetHasTypeList() bool {
	if m != nil {
		return m.HasTypeList
	}
	return false
}

func (m *TablesRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request for Meta#getTableTypes()
type TableTypesRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *TableTypesRequest) Reset()                    { *m = TableTypesRequest{} }
func (m *TableTypesRequest) String() string            { return proto.CompactTextString(m) }
func (*TableTypesRequest) ProtoMessage()               {}
func (*TableTypesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *TableTypesRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request for Meta#getColumns(String, org.apache.calcite.avatica.Meta.Pat,
//   org.apache.calcite.avatica.Meta.Pat, org.apache.calcite.avatica.Meta.Pat).
type ColumnsRequest struct {
	Catalog           string `protobuf:"bytes,1,opt,name=catalog" json:"catalog,omitempty"`
	SchemaPattern     string `protobuf:"bytes,2,opt,name=schema_pattern,json=schemaPattern" json:"schema_pattern,omitempty"`
	TableNamePattern  string `protobuf:"bytes,3,opt,name=table_name_pattern,json=tableNamePattern" json:"table_name_pattern,omitempty"`
	ColumnNamePattern string `protobuf:"bytes,4,opt,name=column_name_pattern,json=columnNamePattern" json:"column_name_pattern,omitempty"`
	ConnectionId      string `protobuf:"bytes,5,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *ColumnsRequest) Reset()                    { *m = ColumnsRequest{} }
func (m *ColumnsRequest) String() string            { return proto.CompactTextString(m) }
func (*ColumnsRequest) ProtoMessage()               {}
func (*ColumnsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ColumnsRequest) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

func (m *ColumnsRequest) GetSchemaPattern() string {
	if m != nil {
		return m.SchemaPattern
	}
	return ""
}

func (m *ColumnsRequest) GetTableNamePattern() string {
	if m != nil {
		return m.TableNamePattern
	}
	return ""
}

func (m *ColumnsRequest) GetColumnNamePattern() string {
	if m != nil {
		return m.ColumnNamePattern
	}
	return ""
}

func (m *ColumnsRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request for Meta#getTypeInfo()
type TypeInfoRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *TypeInfoRequest) Reset()                    { *m = TypeInfoRequest{} }
func (m *TypeInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*TypeInfoRequest) ProtoMessage()               {}
func (*TypeInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *TypeInfoRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request for Meta#prepareAndExecute(Meta.StatementHandle, String, long, Meta.PrepareCallback)
type PrepareAndExecuteRequest struct {
	ConnectionId      string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	Sql               string `protobuf:"bytes,2,opt,name=sql" json:"sql,omitempty"`
	MaxRowCount       uint64 `protobuf:"varint,3,opt,name=max_row_count,json=maxRowCount" json:"max_row_count,omitempty"`
	StatementId       uint32 `protobuf:"varint,4,opt,name=statement_id,json=statementId" json:"statement_id,omitempty"`
	MaxRowsTotal      int64  `protobuf:"varint,5,opt,name=max_rows_total,json=maxRowsTotal" json:"max_rows_total,omitempty"`
	FirstFrameMaxSize int32  `protobuf:"varint,6,opt,name=first_frame_max_size,json=firstFrameMaxSize" json:"first_frame_max_size,omitempty"`
}

func (m *PrepareAndExecuteRequest) Reset()                    { *m = PrepareAndExecuteRequest{} }
func (m *PrepareAndExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*PrepareAndExecuteRequest) ProtoMessage()               {}
func (*PrepareAndExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *PrepareAndExecuteRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *PrepareAndExecuteRequest) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *PrepareAndExecuteRequest) GetMaxRowCount() uint64 {
	if m != nil {
		return m.MaxRowCount
	}
	return 0
}

func (m *PrepareAndExecuteRequest) GetStatementId() uint32 {
	if m != nil {
		return m.StatementId
	}
	return 0
}

func (m *PrepareAndExecuteRequest) GetMaxRowsTotal() int64 {
	if m != nil {
		return m.MaxRowsTotal
	}
	return 0
}

func (m *PrepareAndExecuteRequest) GetFirstFrameMaxSize() int32 {
	if m != nil {
		return m.FirstFrameMaxSize
	}
	return 0
}

// Request for Meta.prepare(Meta.ConnectionHandle, String, long)
type PrepareRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	Sql          string `protobuf:"bytes,2,opt,name=sql" json:"sql,omitempty"`
	MaxRowCount  uint64 `protobuf:"varint,3,opt,name=max_row_count,json=maxRowCount" json:"max_row_count,omitempty"`
	MaxRowsTotal int64  `protobuf:"varint,4,opt,name=max_rows_total,json=maxRowsTotal" json:"max_rows_total,omitempty"`
}

func (m *PrepareRequest) Reset()                    { *m = PrepareRequest{} }
func (m *PrepareRequest) String() string            { return proto.CompactTextString(m) }
func (*PrepareRequest) ProtoMessage()               {}
func (*PrepareRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *PrepareRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *PrepareRequest) GetSql() string {
	if m != nil {
		return m.Sql
	}
	return ""
}

func (m *PrepareRequest) GetMaxRowCount() uint64 {
	if m != nil {
		return m.MaxRowCount
	}
	return 0
}

func (m *PrepareRequest) GetMaxRowsTotal() int64 {
	if m != nil {
		return m.MaxRowsTotal
	}
	return 0
}

// Request for Meta#fetch(Meta.StatementHandle, List, long, int)
type FetchRequest struct {
	ConnectionId     string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	StatementId      uint32 `protobuf:"varint,2,opt,name=statement_id,json=statementId" json:"statement_id,omitempty"`
	Offset           uint64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	FetchMaxRowCount uint32 `protobuf:"varint,4,opt,name=fetch_max_row_count,json=fetchMaxRowCount" json:"fetch_max_row_count,omitempty"`
	FrameMaxSize     int32  `protobuf:"varint,5,opt,name=frame_max_size,json=frameMaxSize" json:"frame_max_size,omitempty"`
}

func (m *FetchRequest) Reset()                    { *m = FetchRequest{} }
func (m *FetchRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()               {}
func (*FetchRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *FetchRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *FetchRequest) GetStatementId() uint32 {
	if m != nil {
		return m.StatementId
	}
	return 0
}

func (m *FetchRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FetchRequest) GetFetchMaxRowCount() uint32 {
	if m != nil {
		return m.FetchMaxRowCount
	}
	return 0
}

func (m *FetchRequest) GetFrameMaxSize() int32 {
	if m != nil {
		return m.FrameMaxSize
	}
	return 0
}

// Request for Meta#createStatement(Meta.ConnectionHandle)
type CreateStatementRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *CreateStatementRequest) Reset()                    { *m = CreateStatementRequest{} }
func (m *CreateStatementRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateStatementRequest) ProtoMessage()               {}
func (*CreateStatementRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *CreateStatementRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request for Meta#closeStatement(Meta.StatementHandle)
type CloseStatementRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	StatementId  uint32 `protobuf:"varint,2,opt,name=statement_id,json=statementId" json:"statement_id,omitempty"`
}

func (m *CloseStatementRequest) Reset()                    { *m = CloseStatementRequest{} }
func (m *CloseStatementRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseStatementRequest) ProtoMessage()               {}
func (*CloseStatementRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *CloseStatementRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *CloseStatementRequest) GetStatementId() uint32 {
	if m != nil {
		return m.StatementId
	}
	return 0
}

// Request for Meta#openConnection(Meta.ConnectionHandle, Map<String, String>)
type OpenConnectionRequest struct {
	ConnectionId string            `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	Info         map[string]string `protobuf:"bytes,2,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *OpenConnectionRequest) Reset()                    { *m = OpenConnectionRequest{} }
func (m *OpenConnectionRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenConnectionRequest) ProtoMessage()               {}
func (*OpenConnectionRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *OpenConnectionRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *OpenConnectionRequest) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

// Request for Meta#closeConnection(Meta.ConnectionHandle)
type CloseConnectionRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *CloseConnectionRequest) Reset()                    { *m = CloseConnectionRequest{} }
func (m *CloseConnectionRequest) String() string            { return proto.CompactTextString(m) }
func (*CloseConnectionRequest) ProtoMessage()               {}
func (*CloseConnectionRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *CloseConnectionRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

type ConnectionSyncRequest struct {
	ConnectionId string                `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	ConnProps    *ConnectionProperties `protobuf:"bytes,2,opt,name=conn_props,json=connProps" json:"conn_props,omitempty"`
}

func (m *ConnectionSyncRequest) Reset()                    { *m = ConnectionSyncRequest{} }
func (m *ConnectionSyncRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectionSyncRequest) ProtoMessage()               {}
func (*ConnectionSyncRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *ConnectionSyncRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *ConnectionSyncRequest) GetConnProps() *ConnectionProperties {
	if m != nil {
		return m.ConnProps
	}
	return nil
}

// Request for Meta#execute(Meta.ConnectionHandle, list, long)
type ExecuteRequest struct {
	StatementHandle    *StatementHandle `protobuf:"bytes,1,opt,name=statementHandle" json:"statementHandle,omitempty"`
	ParameterValues    []*TypedValue    `protobuf:"bytes,2,rep,name=parameter_values,json=parameterValues" json:"parameter_values,omitempty"`
	FirstFrameMaxSize  uint64           `protobuf:"varint,3,opt,name=first_frame_max_size,json=firstFrameMaxSize" json:"first_frame_max_size,omitempty"`
	HasParameterValues bool             `protobuf:"varint,4,opt,name=has_parameter_values,json=hasParameterValues" json:"has_parameter_values,omitempty"`
}

func (m *ExecuteRequest) Reset()                    { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()               {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *ExecuteRequest) GetStatementHandle() *StatementHandle {
	if m != nil {
		return m.StatementHandle
	}
	return nil
}

func (m *ExecuteRequest) GetParameterValues() []*TypedValue {
	if m != nil {
		return m.ParameterValues
	}
	return nil
}

func (m *ExecuteRequest) GetFirstFrameMaxSize() uint64 {
	if m != nil {
		return m.FirstFrameMaxSize
	}
	return 0
}

func (m *ExecuteRequest) GetHasParameterValues() bool {
	if m != nil {
		return m.HasParameterValues
	}
	return false
}

type SyncResultsRequest struct {
	ConnectionId string      `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	StatementId  uint32      `protobuf:"varint,2,opt,name=statement_id,json=statementId" json:"statement_id,omitempty"`
	State        *QueryState `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Offset       uint64      `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SyncResultsRequest) Reset()                    { *m = SyncResultsRequest{} }
func (m *SyncResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncResultsRequest) ProtoMessage()               {}
func (*SyncResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *SyncResultsRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *SyncResultsRequest) GetStatementId() uint32 {
	if m != nil {
		return m.StatementId
	}
	return 0
}

func (m *SyncResultsRequest) GetState() *QueryState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *SyncResultsRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// Request to invoke a commit on a Connection
type CommitRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *CommitRequest) Reset()                    { *m = CommitRequest{} }
func (m *CommitRequest) String() string            { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()               {}
func (*CommitRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *CommitRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request to invoke rollback on a Connection
type RollbackRequest struct {
	ConnectionId string `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
}

func (m *RollbackRequest) Reset()                    { *m = RollbackRequest{} }
func (m *RollbackRequest) String() string            { return proto.CompactTextString(m) }
func (*RollbackRequest) ProtoMessage()               {}
func (*RollbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *RollbackRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

// Request to prepare and execute a collection of sql statements.
type PrepareAndExecuteBatchRequest struct {
	ConnectionId string   `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	StatementId  uint32   `protobuf:"varint,2,opt,name=statement_id,json=statementId" json:"statement_id,omitempty"`
	SqlCommands  []string `protobuf:"bytes,3,rep,name=sql_commands,json=sqlCommands" json:"sql_commands,omitempty"`
}

func (m *PrepareAndExecuteBatchRequest) Reset()                    { *m = PrepareAndExecuteBatchRequest{} }
func (m *PrepareAndExecuteBatchRequest) String() string            { return proto.CompactTextString(m) }
func (*PrepareAndExecuteBatchRequest) ProtoMessage()               {}
func (*PrepareAndExecuteBatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *PrepareAndExecuteBatchRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *PrepareAndExecuteBatchRequest) GetStatementId() uint32 {
	if m != nil {
		return m.StatementId
	}
	return 0
}

func (m *PrepareAndExecuteBatchRequest) GetSqlCommands() []string {
	if m != nil {
		return m.SqlCommands
	}
	return nil
}

// Each command is a list of TypedValues
type UpdateBatch struct {
	ParameterValues []*TypedValue `protobuf:"bytes,1,rep,name=parameter_values,json=parameterValues" json:"parameter_values,omitempty"`
}

func (m *UpdateBatch) Reset()                    { *m = UpdateBatch{} }
func (m *UpdateBatch) String() string            { return proto.CompactTextString(m) }
func (*UpdateBatch) ProtoMessage()               {}
func (*UpdateBatch) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *UpdateBatch) GetParameterValues() []*TypedValue {
	if m != nil {
		return m.ParameterValues
	}
	return nil
}

type ExecuteBatchRequest struct {
	ConnectionId string         `protobuf:"bytes,1,opt,name=connection_id,json=connectionId" json:"connection_id,omitempty"`
	StatementId  uint32         `protobuf:"varint,2,opt,name=statement_id,json=statementId" json:"statement_id,omitempty"`
	Updates      []*UpdateBatch `protobuf:"bytes,3,rep,name=updates" json:"updates,omitempty"`
}

func (m *ExecuteBatchRequest) Reset()                    { *m = ExecuteBatchRequest{} }
func (m *ExecuteBatchRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteBatchRequest) ProtoMessage()               {}
func (*ExecuteBatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *ExecuteBatchRequest) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

func (m *ExecuteBatchRequest) GetStatementId() uint32 {
	if m != nil {
		return m.StatementId
	}
	return 0
}

func (m *ExecuteBatchRequest) GetUpdates() []*UpdateBatch {
	if m != nil {
		return m.Updates
	}
	return nil
}

func init() {
	proto.RegisterType((*CatalogsRequest)(nil), "CatalogsRequest")
	proto.RegisterType((*DatabasePropertyRequest)(nil), "DatabasePropertyRequest")
	proto.RegisterType((*SchemasRequest)(nil), "SchemasRequest")
	proto.RegisterType((*TablesRequest)(nil), "TablesRequest")
	proto.RegisterType((*TableTypesRequest)(nil), "TableTypesRequest")
	proto.RegisterType((*ColumnsRequest)(nil), "ColumnsRequest")
	proto.RegisterType((*TypeInfoRequest)(nil), "TypeInfoRequest")
	proto.RegisterType((*PrepareAndExecuteRequest)(nil), "PrepareAndExecuteRequest")
	proto.RegisterType((*PrepareRequest)(nil), "PrepareRequest")
	proto.RegisterType((*FetchRequest)(nil), "FetchRequest")
	proto.RegisterType((*CreateStatementRequest)(nil), "CreateStatementRequest")
	proto.RegisterType((*CloseStatementRequest)(nil), "CloseStatementRequest")
	proto.RegisterType((*OpenConnectionRequest)(nil), "OpenConnectionRequest")
	proto.RegisterType((*CloseConnectionRequest)(nil), "CloseConnectionRequest")
	proto.RegisterType((*ConnectionSyncRequest)(nil), "ConnectionSyncRequest")
	proto.RegisterType((*ExecuteRequest)(nil), "ExecuteRequest")
	proto.RegisterType((*SyncResultsRequest)(nil), "SyncResultsRequest")
	proto.RegisterType((*CommitRequest)(nil), "CommitRequest")
	proto.RegisterType((*RollbackRequest)(nil), "RollbackRequest")
	proto.RegisterType((*PrepareAndExecuteBatchRequest)(nil), "PrepareAndExecuteBatchRequest")
	proto.RegisterType((*UpdateBatch)(nil), "UpdateBatch")
	proto.RegisterType((*ExecuteBatchRequest)(nil), "ExecuteBatchRequest")
}

func init() { proto.RegisterFile("requests.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 883 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0x96, 0x9b, 0xa4, 0xdd, 0x1c, 0xe7, 0xaf, 0x6e, 0xbb, 0x44, 0x8b, 0x90, 0xb2, 0xe6, 0x47,
	0xbd, 0x00, 0x83, 0xca, 0xaa, 0xac, 0x56, 0x02, 0x89, 0x0d, 0x5d, 0x51, 0x89, 0x85, 0xe2, 0x14,
	0x6e, 0xad, 0x53, 0xe7, 0x64, 0x63, 0xad, 0x3d, 0xe3, 0xce, 0x8c, 0xbb, 0xcd, 0xde, 0x73, 0xc3,
	0x1d, 0x57, 0x3c, 0x04, 0x8f, 0xc1, 0x2b, 0xf0, 0x08, 0x48, 0x5c, 0xf2, 0x0a, 0x68, 0xc6, 0x4e,
	0x9a, 0xc4, 0x41, 0xe0, 0xd5, 0x16, 0xae, 0x92, 0x73, 0xe6, 0x3b, 0x3f, 0xdf, 0x37, 0x67, 0x66,
	0x0c, 0x1d, 0x41, 0x97, 0x19, 0x49, 0x25, 0xbd, 0x54, 0x70, 0xc5, 0xef, 0xb5, 0x42, 0x9e, 0x24,
	0x9c, 0xe5, 0x96, 0x7b, 0x0c, 0xdd, 0x21, 0x2a, 0x8c, 0xf9, 0x33, 0xe9, 0xe7, 0x38, 0xe7, 0x6d,
	0x68, 0x87, 0x9c, 0x31, 0x0a, 0x55, 0xc4, 0x59, 0x10, 0x8d, 0xfb, 0xd6, 0xc0, 0x3a, 0x6c, 0xfa,
	0xad, 0x1b, 0xe7, 0xe9, 0xd8, 0xfd, 0x0c, 0xde, 0xf8, 0x02, 0x15, 0x5e, 0xa0, 0xa4, 0x33, 0xc1,
	0x53, 0x12, 0x6a, 0x56, 0x29, 0xfe, 0x0a, 0x3a, 0xa3, 0x70, 0x4a, 0x09, 0x2e, 0xca, 0xf6, 0x61,
	0x27, 0xcc, 0x3b, 0x29, 0x02, 0xe6, 0xa6, 0xf3, 0x2e, 0x74, 0xa4, 0xc1, 0x06, 0x29, 0x2a, 0x45,
	0x82, 0xf5, 0xb7, 0x0c, 0xa0, 0x9d, 0x7b, 0xcf, 0x72, 0x67, 0xb9, 0x6e, 0x6d, 0x43, 0xdd, 0xdf,
	0x2d, 0x68, 0x9f, 0xe3, 0x45, 0x4c, 0xaf, 0xaf, 0xee, 0xfb, 0xe0, 0x28, 0x9d, 0x31, 0x60, 0x98,
	0xd0, 0x02, 0x9a, 0x17, 0xef, 0x99, 0x95, 0xaf, 0x31, 0xa1, 0x39, 0xfa, 0x4d, 0x68, 0xaa, 0x59,
	0x4a, 0x41, 0x1c, 0x49, 0xd5, 0xaf, 0x0f, 0x6a, 0x87, 0x4d, 0xff, 0x8e, 0x76, 0x7c, 0x15, 0x49,
	0xe5, 0xb8, 0xd0, 0x9e, 0xa2, 0x0c, 0x6e, 0x00, 0xdb, 0x03, 0xeb, 0xf0, 0x8e, 0x6f, 0x4f, 0x51,
	0x9e, 0xcf, 0x31, 0x25, 0x9a, 0x3b, 0x1b, 0x68, 0x3e, 0x84, 0x5d, 0xc3, 0x52, 0x47, 0x55, 0xdb,
	0xd8, 0xdf, 0x2c, 0xe8, 0x0c, 0x79, 0x9c, 0x25, 0xec, 0xff, 0x52, 0xc8, 0x83, 0xbd, 0xd0, 0x34,
	0xb0, 0x0a, 0xaf, 0x1b, 0xf8, 0x6e, 0xbe, 0xb4, 0x8c, 0x2f, 0xd1, 0x6a, 0x6c, 0xa0, 0x75, 0x0c,
	0x5d, 0xad, 0xc5, 0x29, 0x9b, 0xf0, 0x4a, 0x72, 0xfc, 0x69, 0x41, 0xff, 0x4c, 0x50, 0x8a, 0x82,
	0x3e, 0x67, 0xe3, 0x93, 0x6b, 0x0a, 0x33, 0x45, 0x55, 0x32, 0x38, 0x3d, 0xa8, 0xc9, 0xcb, 0xb8,
	0x10, 0x46, 0xff, 0xd5, 0xbb, 0x9c, 0xe0, 0x75, 0x20, 0xf8, 0x8b, 0x20, 0xe4, 0x19, 0x53, 0x46,
	0x89, 0xba, 0x6f, 0x27, 0x78, 0xed, 0xf3, 0x17, 0x43, 0xed, 0x72, 0xee, 0x43, 0x4b, 0x2a, 0x54,
	0x94, 0x10, 0x53, 0x3a, 0xb3, 0x66, 0xdf, 0xf6, 0xed, 0x85, 0xef, 0x74, 0xec, 0xbc, 0x03, 0x9d,
	0x22, 0x8d, 0x0c, 0x14, 0x57, 0x18, 0x1b, 0xe2, 0x35, 0xbf, 0x95, 0xe7, 0x91, 0xe7, 0xda, 0xe7,
	0x7c, 0x08, 0xfb, 0x93, 0x48, 0x48, 0x15, 0x4c, 0x84, 0x56, 0x53, 0x47, 0xc8, 0xe8, 0x25, 0x99,
	0xc9, 0x6a, 0xf8, 0xbb, 0x66, 0xed, 0x89, 0x5e, 0x7a, 0x8a, 0xd7, 0xa3, 0xe8, 0x25, 0xb9, 0x3f,
	0x59, 0xd0, 0x29, 0x18, 0xff, 0x07, 0x3c, 0xcb, 0x24, 0xea, 0x65, 0x12, 0xee, 0xaf, 0x16, 0xb4,
	0x9e, 0x90, 0x0a, 0xa7, 0x95, 0x3a, 0x5a, 0xd7, 0x70, 0xab, 0xac, 0xe1, 0x5d, 0xd8, 0xe6, 0x93,
	0x89, 0xa4, 0x79, 0x6f, 0x85, 0xe5, 0x7c, 0x00, 0x7b, 0x13, 0x5d, 0x2f, 0x58, 0x25, 0x90, 0xef,
	0x42, 0xcf, 0x2c, 0x3d, 0x5d, 0x65, 0xb1, 0x26, 0x6f, 0xc3, 0xc8, 0xdb, 0x9a, 0x2c, 0x2b, 0xfb,
	0x29, 0xdc, 0x1d, 0x0a, 0x42, 0x45, 0xa3, 0x79, 0x07, 0x95, 0x46, 0x31, 0x80, 0x83, 0x61, 0xcc,
	0xe5, 0xab, 0x45, 0xff, 0x0b, 0x31, 0xdc, 0x5f, 0x2c, 0x38, 0xf8, 0x26, 0x25, 0x36, 0x5c, 0xc4,
	0x55, 0xaa, 0xf0, 0x00, 0xea, 0x11, 0x9b, 0xf0, 0xfe, 0xd6, 0xa0, 0x76, 0x68, 0x1f, 0x0d, 0xbc,
	0x8d, 0xa9, 0x3c, 0x7d, 0x02, 0x4f, 0x98, 0x12, 0x33, 0xdf, 0xa0, 0xef, 0x7d, 0x02, 0xcd, 0x85,
	0x4b, 0xcf, 0xd0, 0x73, 0x9a, 0x15, 0xd9, 0xf5, 0x5f, 0x67, 0x1f, 0x1a, 0x57, 0x18, 0x67, 0x54,
	0xcc, 0x55, 0x6e, 0x3c, 0xda, 0x7a, 0x68, 0x19, 0x35, 0xb5, 0x1c, 0xaf, 0xd6, 0xad, 0x2b, 0xe0,
	0xe0, 0x26, 0x72, 0x34, 0x63, 0x61, 0x45, 0xae, 0xa0, 0xed, 0x20, 0x15, 0x3c, 0x95, 0xa6, 0x37,
	0xfb, 0xe8, 0xc0, 0xbb, 0x49, 0x58, 0xbc, 0x89, 0x11, 0x49, 0xbf, 0xa9, 0x81, 0xda, 0x96, 0xee,
	0x1f, 0x16, 0x74, 0xd6, 0xae, 0x90, 0x47, 0xd0, 0x5d, 0x6c, 0xc1, 0x97, 0xc8, 0xc6, 0x31, 0x99,
	0x7a, 0xf6, 0x51, 0xcf, 0x1b, 0xad, 0xfa, 0xfd, 0x75, 0xa0, 0x73, 0x0c, 0xbd, 0x14, 0xf5, 0x80,
	0x29, 0x12, 0x81, 0x11, 0x46, 0x16, 0xe2, 0xdb, 0x9e, 0xbe, 0xec, 0xc6, 0xdf, 0x6b, 0x9f, 0xdf,
	0x5d, 0x80, 0x8c, 0x2d, 0xff, 0xf6, 0x4a, 0xc8, 0x8f, 0x40, 0xf9, 0x4a, 0x70, 0x3e, 0x82, 0x7d,
	0xfd, 0x2c, 0x95, 0x8a, 0xd5, 0xcd, 0xeb, 0xe4, 0x4c, 0x51, 0x9e, 0xad, 0x96, 0x70, 0x7f, 0xb6,
	0xc0, 0xc9, 0x45, 0x95, 0x59, 0xac, 0xe4, 0xeb, 0x3e, 0xb6, 0xf7, 0xa1, 0x61, 0x4c, 0xd3, 0xb2,
	0xa6, 0xfb, 0x6d, 0x46, 0x62, 0x66, 0x04, 0xf3, 0xf3, 0x95, 0xa5, 0x93, 0x5d, 0x5f, 0x3e, 0xd9,
	0xee, 0x03, 0x68, 0x0f, 0x79, 0x92, 0x44, 0xd5, 0xce, 0xde, 0x31, 0x74, 0x7d, 0x1e, 0xc7, 0x17,
	0x18, 0x3e, 0xaf, 0x14, 0xf7, 0xa3, 0x05, 0x6f, 0x95, 0x9e, 0x8f, 0xc7, 0x78, 0x0b, 0x37, 0x99,
	0x86, 0x5c, 0xc6, 0x81, 0xfe, 0xb8, 0x43, 0x36, 0x96, 0xfd, 0x9a, 0xf9, 0xb4, 0xb0, 0xe5, 0x65,
	0x3c, 0x2c, 0x5c, 0xee, 0x09, 0xd8, 0xdf, 0xa5, 0x63, 0x2c, 0x1a, 0xd8, 0x38, 0x3e, 0xd6, 0x3f,
	0x8f, 0x8f, 0xfb, 0x83, 0x05, 0x7b, 0xb7, 0xc9, 0xe4, 0x3d, 0xd8, 0xc9, 0x4c, 0x9b, 0x39, 0x09,
	0xfb, 0xa8, 0xe5, 0x2d, 0xb5, 0xed, 0xcf, 0x17, 0x1f, 0xbb, 0x30, 0xe0, 0xe2, 0x99, 0x87, 0x29,
	0x86, 0x53, 0xf2, 0x42, 0x8c, 0xc3, 0x48, 0x91, 0x87, 0x57, 0xa8, 0xa2, 0x10, 0xf3, 0xcf, 0xdb,
	0x8b, 0x6d, 0xf3, 0xf3, 0xf1, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x49, 0xad, 0x3d, 0x05,
	0x0b, 0x00, 0x00,
}
