name: Test

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go_version: [1.11, 1.12]
        database_image:
          - boostport/hbase-phoenix-all-in-one:1.3-4.13
          - boostport/hbase-phoenix-all-in-one:1.4-4.14
          - boostport/hbase-phoenix-all-in-one:2.0-5.0
          - f21global/calcite-avatica:1.11.0-hypersql
          - f21global/calcite-avatica:1.12.0-hypersql
          - apache/calcite-avatica-hypersql:1.13.0
          - apache/calcite-avatica-hypersql:1.14.0
          - apache/calcite-avatica-hypersql:1.15.0

    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Show go path
        run: echo ${{ go.module-path }}

      - name: Checking out Avatica-Go repository
        uses: actions/checkout@v1

      - name: Start database
        env:
          database_image: ${{ matrix.database_image }}
        run: |
          docker pull $database_image;

          if [[ $database_image =~ phoenix ]]; then
            docker run -d -p 8765:8765 $database_image;
          elif [ $AVATICA_FLAVOR == hypersql ]; then
            docker run -d -p 8765:8765 $database_image -u jdbc:hsqldb:mem:public;
          fi

      - name: Run tests
        run: go test -v ./...